/**
 * DIY 文案入口（后台）
 *
 * 用法：
 * 1. 后台页面出现可见文案，优先放到这里再在组件中引用。
 * 2. 该文件是运营/设计同学改文案的首选入口，避免在多个 Vue 文件里到处找字符串。
 */

export const adminCopy = {
  layout: {
    defaultPageTitle: '仪表盘',
  },
  backup: {
    title: '数据导出与备份',
    subtitle: '一键导出 JSON 或 SQL 备份，方便迁移与灾备。',
    jsonCardTitle: 'JSON 备份',
    jsonCardDescription: '导出结构化 JSON，适合审计与跨环境传输。',
    sqlCardTitle: 'SQL 备份',
    sqlCardDescription: '导出可直接回放的 SQL 脚本，适合完整恢复。',
    jsonButton: '导出 JSON',
    sqlButton: '导出 SQL',
    exporting: '导出中...',
    success: '备份导出成功',
    failed: '备份导出失败，请稍后重试',
  },
  moderation: {
    rateLimit: {
      title: 'Redis 限流观测',
      subtitle: '最近窗口的放行/拦截趋势与规则命中分布。',
      refresh: '刷新',
      loading: '加载中...',
      totalAllowed: '放行总数',
      totalBlocked: '拦截总数',
      ruleTitle: '规则命中',
      trendTitle: '分钟趋势',
      noData: '暂无限流数据',
      allowedLegend: '放行',
      blockedLegend: '拦截',
      ruleColumn: '规则',
      allowedColumn: '放行',
      blockedColumn: '拦截',
      totalColumn: '总计',
    },
  },
  dashboard: {
    toolbar: {
      filter: 'Filter',
      prevWindowAria: '上一时间窗口',
      nextWindowAria: '下一时间窗口',
      pathFilter: 'Path Filter',
      pathPlaceholder: '输入路径关键字',
    },
    sections: {
      trafficOverviewTitle: 'Traffic Overview',
      trafficOverviewSubtitle: 'Visitors 和 Views 的时间分布',
      recentActivitiesTitle: '近期事项',
      recentActivitiesSubtitle: '管理员最近操作记录',
      pages: 'Pages',
      sources: 'Sources',
      environment: 'Environment',
      location: 'Location',
      geoDistribution: 'Geo Distribution',
      byCountry: 'By Country',
      traffic: 'Traffic',
    },
    ranges: {
      h24: 'Last 24 hours',
      d7: 'Last 7 days',
      d30: 'Last 30 days',
    },
    tabs: {
      path: 'Path',
      entry: 'Entry',
      exit: 'Exit',
      referrers: 'Referrers',
      channels: 'Channels',
      browsers: 'Browsers',
      os: 'OS',
      devices: 'Devices',
      countries: 'Countries',
      regions: 'Regions',
      cities: 'Cities',
    },
    table: {
      path: 'Path',
      source: 'Source',
      name: 'Name',
      region: 'Region',
      visitors: 'Visitors',
      percent: '%',
    },
    stats: {
      visitors: 'Visitors',
      visits: 'Visits',
      views: 'Views',
      bounceRate: 'Bounce rate',
      visitDuration: 'Visit duration',
    },
    actions: {
      approve: '通过了',
      reject: '拒绝了',
      delete: '删除了',
      create: '创建了',
      update: '更新了',
      publish: '发布了',
      unpublish: '下架了',
      schedule: '定时发布了',
    },
    targets: {
      comment: '评论',
      post: '文章',
      friend_link: '友链',
      guestbook: '留言',
      moment: '说说',
    },
    notices: {
      pendingPrefix: '评论留言待审核：',
      pendingSuffix: ' 条',
      pendingSubtitle: '建议优先处理审核队列，避免积压',
      draftPrefix: '草稿待发布：',
      draftSuffix: ' 篇',
      draftSubtitle: '可前往文章管理检查内容后发布',
    },
    mapFallback: {
      loading: '世界地图加载中...',
      empty: '暂无国家分布数据',
      failed: '无法加载地图底图，已在下方显示国家排行',
    },
    common: {
      loading: '加载中...',
      emptyActivities: '暂无操作记录',
      operatorPrefix: '操作人：',
      activityTargetPrefix: '一条',
      unknown: 'Unknown',
      windowFallback: 'Window',
      less: 'Less',
      more: 'More',
      justNow: '刚刚',
      minutesAgo: '分钟前',
      hoursAgo: '小时前',
      daysAgo: '天前',
      noData: '--',
    },
    degradedMessage: 'Analytics 数据暂不可用，当前显示占位数据。请先在 `backend` 目录执行 `go run cmd/migrate/main.go`。',
  },
  profileManager: {
    page: {
      title: '个人设置',
      subtitle: '在这里统一维护后台身份与登录账号信息。',
    },
    profile: {
      title: '展示身份',
      subtitle: '文章、说说、关于页与博客列表将自动同步这里的昵称和头像。',
      displayNameLabel: '昵称',
      displayNamePlaceholder: '请输入展示昵称',
      avatarLabel: '头像 URL',
      avatarPlaceholder: '请输入头像链接，留空将使用默认头像',
      saveButton: '保存身份',
      savingButton: '保存中...',
      saveSuccess: '管理员身份已更新',
      saveFailed: '保存管理员身份失败，请稍后重试',
      emptyNameError: '昵称不能为空',
      avatarAlt: '管理员头像预览',
    },
    account: {
      title: '登录账号设置',
      subtitle: '可在这里更新登录用户名、邮箱和密码。',
      usernameLabel: '登录用户名',
      usernamePlaceholder: '请输入登录用户名',
      emailLabel: '登录邮箱',
      emailPlaceholder: '请输入登录邮箱',
      passwordLabel: '新密码',
      passwordPlaceholder: '留空则不修改密码',
      saveButton: '保存账号',
      savingButton: '保存中...',
      saveSuccess: '登录账号已更新',
      sessionRevokedSuccess: '登录账号已更新，请重新登录后台',
      saveFailed: '更新登录账号失败，请稍后重试',
      emptyUsernameError: '登录用户名不能为空',
      emptyEmailError: '登录邮箱不能为空',
    },
  },
  footerManager: {
    page: {
      title: '页尾与站点设置',
      subtitle: '在这里统一维护站点品牌、默认 SEO 与页尾文案，保存后前台页面会同步使用。',
      metaTitle: '页尾与站点设置 | Miku Blog',
      metaDescription: '后台站点品牌、默认 SEO 与页尾设置',
    },
    siteProfile: {
      title: '站点品牌与默认 SEO',
      subtitle: '这里维护运行时品牌显示、默认标题后缀、默认描述与分享图，前台会优先读取这里的真实配置。',
      brandTitle: '品牌信息',
      brandHint: '用于导航栏、页尾与运行时品牌展示同步。',
      brandTextLabel: '品牌展示名',
      brandTextPlaceholder: '例如：NanaMiku Blog',
      siteTitleLabel: '站点标题',
      siteTitlePlaceholder: '用于标题后缀、RSS 与默认 SEO 口径',
      logoAltLabel: 'Logo Alt 文案',
      logoAltPlaceholder: '例如：NanaMiku Blog logo',
      seoTitle: '默认 SEO',
      seoHint: '用于 canonical 基准、默认描述与默认分享图回退。',
      siteUrlLabel: '站点 URL',
      siteUrlPlaceholder: '例如：https://nanamiku.blog',
      defaultDescriptionLabel: '默认描述',
      defaultDescriptionPlaceholder: '请输入站点默认 SEO 描述',
      defaultSocialImageLabel: '默认分享图',
      defaultSocialImagePlaceholder: '支持相对路径或完整图片 URL',
      saveButton: '保存站点配置',
      saveButtonAria: '保存站点品牌与默认 SEO 配置',
      savingButton: '保存中...',
      resetButton: '恢复默认站点配置',
      resetButtonAria: '恢复默认站点品牌与默认 SEO 配置',
      validationRequired: '请至少填写品牌展示名、站点标题、站点 URL、默认描述和默认分享图。',
    },
    form: {
      icpTitle: '备案信息',
      icpHint: '如暂未备案可留空；已备案时再填写备案号与备案查询地址。',
      icpLabel: '备案号',
      icpPlaceholder: '暂未备案可留空',
      icpLinkLabel: '备案链接',
      icpLinkPlaceholder: '已备案时再填写查询链接',
      customTitle: '自定义文案',
      customHint: '可添加多行页尾说明文案，例如版权声明、联系方式或运营提示。',
      customLineLabelPrefix: '页尾文案第 ',
      customLinePlaceholder: '输入一行页尾文案',
      emptyCustomHint: '还没有自定义文案，点击“添加文案”即可新增。',
      addButton: '+ 添加文案',
      addButtonAria: '添加页尾文案',
      removeButton: '删除',
      removeButtonAria: '删除这条页尾文案',
      saveButton: '保存页尾配置',
      saveButtonAria: '保存页尾配置',
      savingButton: '保存中...',
      resetButton: '恢复默认',
      resetButtonAria: '恢复默认页尾配置',
    },
    toast: {
      saveSuccess: '页尾配置已保存',
      saveFailed: '页尾配置保存失败，请稍后重试',
      resetSuccess: '已恢复默认页尾配置',
    },
    siteProfileToast: {
      saveSuccess: '站点品牌与默认 SEO 已保存',
      saveFailed: '站点品牌与默认 SEO 保存失败，请稍后重试',
      resetSuccess: '已恢复默认站点品牌与默认 SEO 配置',
    },
  },
  friendsManager: {
    page: {
      title: '友链管理',
      subtitle: '维护友链展示、申请审核和站点健康检查。',
      metaTitle: '友链管理 | Miku Blog',
      metaDescription: '后台友链管理',
      addButton: '+ 添加友链',
      addButtonAria: '添加友链',
    },
    forms: {
      createTitle: '添加友链',
      editTitle: '编辑友链',
      namePlaceholder: '站点名称 *',
      urlPlaceholder: '站点 URL *',
      avatarPlaceholder: '头像 URL',
      descriptionPlaceholder: '站点描述',
      sortPlaceholder: '排序值（越小越靠前）',
      createButton: '添加友链',
      creatingButton: '添加中...',
      updateButton: '保存修改',
      updatingButton: '保存中...',
      cancelButton: '取消',
    },
    stats: {
      approved: '已通过',
      pending: '待审核',
      down: '异常 / 不可达',
    },
    applications: {
      title: '申请队列',
      subtitle: '前台提交的友链申请会进入这里，审核通过后自动转为正式友链。',
      empty: '暂时没有友链申请',
      columns: {
        site: '站点',
        contact: '联系信息',
        description: '说明',
        status: '状态',
        createdAt: '提交时间',
        actions: '操作',
      },
      approveButton: '通过',
      rejectButton: '拒绝',
      processingButton: '处理中...',
      reviewedPrefix: '审核时间：',
      notePrefix: '备注：',
    },
    links: {
      tableTitle: '正式友链',
      empty: '还没有友链记录',
      columns: {
        name: '站点名称',
        url: '链接',
        status: '状态',
        health: '健康检测',
        createdAt: '添加时间',
        actions: '操作',
      },
      approveButton: '通过',
      rejectButton: '拒绝',
      editButton: '编辑',
      deleteButton: '删除',
      healthOk: '正常',
      healthDown: '不可达',
    },
    status: {
      approved: '已通过',
      pending: '待审核',
      rejected: '已拒绝',
    },
    toasts: {
      loadFriendsFailed: '加载友链列表失败',
      loadApplicationsFailed: '加载申请列表失败',
      createSuccess: '友链添加成功',
      createFailed: '添加友链失败',
      updateSuccess: '友链更新成功',
      updateFailed: '更新友链失败',
      deleteSuccess: '友链已删除',
      deleteFailed: '删除失败',
      approveFriendSuccess: '友链已通过',
      rejectFriendSuccess: '友链已拒绝',
      approveApplicationSuccess: '申请已通过并转为正式友链',
      rejectApplicationSuccess: '申请已拒绝',
    },
  },
  momentsManager: {
    profile: {
      title: '管理员说说身份',
      subtitle: '发布说说时会自动使用这里的昵称与头像。',
      displayNameLabel: '昵称',
      displayNamePlaceholder: '请输入展示昵称',
      avatarLabel: '头像 URL',
      avatarPlaceholder: '请输入头像链接，留空将使用默认头像',
      saveButton: '保存身份',
      savingButton: '保存中...',
      saveSuccess: '管理员身份已更新',
      saveFailed: '保存管理员身份失败，请稍后重试',
      emptyNameError: '昵称不能为空',
      avatarAlt: '管理员头像预览',
      autoHint: '发布说说时自动带入管理员昵称与头像',
    },
    account: {
      title: '登录账号设置',
      subtitle: '可在这里更新登录用户名、邮箱和密码。',
      usernameLabel: '登录用户名',
      usernamePlaceholder: '请输入登录用户名',
      emailLabel: '登录邮箱',
      emailPlaceholder: '请输入登录邮箱',
      passwordLabel: '新密码',
      passwordPlaceholder: '留空则不修改密码',
      saveButton: '保存账号',
      savingButton: '保存中...',
      saveSuccess: '登录账号已更新',
      saveFailed: '更新登录账号失败，请稍后重试',
      emptyUsernameError: '登录用户名不能为空',
      emptyEmailError: '登录邮箱不能为空',
    },
    actions: {
      deleteButton: '删除',
      deleteAria: '删除说说',
      deleteConfirm: '确认删除这条说说吗？删除后无法恢复。',
      deleteSuccess: '说说已删除',
      deleteFailed: '删除说说失败，请稍后重试',
    },
  },
}
