/**
 * DIY 文案入口（后台）
 *
 * 用法：
 * 1. 后台页面出现可见文案，优先放到这里再在组件中引用。
 * 2. 该文件是运营/设计同学改文案的首选入口，避免在多个 Vue 文件里到处找字符串。
 */

export const adminCopy = {
  layout: {
    defaultPageTitle: '仪表盘',
  },
  backup: {
    title: '数据导出与备份',
    subtitle: '一键导出 JSON 或 SQL 备份，方便迁移与灾备。',
    jsonCardTitle: 'JSON 备份',
    jsonCardDescription: '导出结构化 JSON，适合审计与跨环境传输。',
    sqlCardTitle: 'SQL 备份',
    sqlCardDescription: '导出可直接回放的 SQL 脚本，适合完整恢复。',
    jsonButton: '导出 JSON',
    sqlButton: '导出 SQL',
    exporting: '导出中...',
    success: '备份导出成功',
    failed: '备份导出失败，请稍后重试',
  },
  moderation: {
    rateLimit: {
      title: 'Redis 限流观测',
      subtitle: '最近窗口的放行/拦截趋势与规则命中分布。',
      refresh: '刷新',
      loading: '加载中...',
      totalAllowed: '放行总数',
      totalBlocked: '拦截总数',
      ruleTitle: '规则命中',
      trendTitle: '分钟趋势',
      noData: '暂无限流数据',
      allowedLegend: '放行',
      blockedLegend: '拦截',
      ruleColumn: '规则',
      allowedColumn: '放行',
      blockedColumn: '拦截',
      totalColumn: '总计',
    },
  },
  dashboard: {
    toolbar: {
      filter: 'Filter',
      prevWindowAria: '上一时间窗口',
      nextWindowAria: '下一时间窗口',
      pathFilter: 'Path Filter',
      pathPlaceholder: '输入路径关键字',
    },
    sections: {
      trafficOverviewTitle: 'Traffic Overview',
      trafficOverviewSubtitle: 'Visitors 和 Views 的时间分布',
      recentActivitiesTitle: '近期事项',
      recentActivitiesSubtitle: '管理员最近操作记录',
      pages: 'Pages',
      sources: 'Sources',
      environment: 'Environment',
      location: 'Location',
      geoDistribution: 'Geo Distribution',
      byCountry: 'By Country',
      traffic: 'Traffic',
    },
    ranges: {
      h24: 'Last 24 hours',
      d7: 'Last 7 days',
      d30: 'Last 30 days',
    },
    tabs: {
      path: 'Path',
      entry: 'Entry',
      exit: 'Exit',
      referrers: 'Referrers',
      channels: 'Channels',
      browsers: 'Browsers',
      os: 'OS',
      devices: 'Devices',
      countries: 'Countries',
      regions: 'Regions',
      cities: 'Cities',
    },
    table: {
      path: 'Path',
      source: 'Source',
      name: 'Name',
      region: 'Region',
      visitors: 'Visitors',
      percent: '%',
    },
    stats: {
      visitors: 'Visitors',
      visits: 'Visits',
      views: 'Views',
      bounceRate: 'Bounce rate',
      visitDuration: 'Visit duration',
    },
    actions: {
      approve: '通过了',
      reject: '拒绝了',
      delete: '删除了',
      create: '创建了',
      update: '更新了',
      publish: '发布了',
      unpublish: '下架了',
      schedule: '定时发布了',
    },
    targets: {
      comment: '评论',
      post: '文章',
      friend_link: '友链',
      guestbook: '留言',
      moment: '说说',
    },
    notices: {
      pendingPrefix: '评论留言待审核：',
      pendingSuffix: ' 条',
      pendingSubtitle: '建议优先处理审核队列，避免积压',
      draftPrefix: '草稿待发布：',
      draftSuffix: ' 篇',
      draftSubtitle: '可前往文章管理检查内容后发布',
    },
    mapFallback: {
      loading: '世界地图加载中...',
      empty: '暂无国家分布数据',
      failed: '无法加载地图底图，已在下方显示国家排行',
    },
    common: {
      loading: '加载中...',
      emptyActivities: '暂无操作记录',
      operatorPrefix: '操作人：',
      activityTargetPrefix: '一条',
      unknown: 'Unknown',
      windowFallback: 'Window',
      less: 'Less',
      more: 'More',
      justNow: '刚刚',
      minutesAgo: '分钟前',
      hoursAgo: '小时前',
      daysAgo: '天前',
      noData: '--',
    },
    degradedMessage: 'Analytics 数据暂不可用，当前显示占位数据。请先在 `backend` 目录执行 `go run cmd/migrate/main.go`。',
  },
  profileManager: {
    page: {
      title: '个人设置',
      subtitle: '在这里统一维护后台身份与登录账号信息。',
    },
    profile: {
      title: '展示身份',
      subtitle: '文章、说说、关于页与博客列表将自动同步这里的昵称和头像。',
      displayNameLabel: '昵称',
      displayNamePlaceholder: '请输入展示昵称',
      avatarLabel: '头像 URL',
      avatarPlaceholder: '请输入头像链接，留空将使用默认头像',
      saveButton: '保存身份',
      savingButton: '保存中...',
      saveSuccess: '管理员身份已更新',
      saveFailed: '保存管理员身份失败，请稍后重试',
      emptyNameError: '昵称不能为空',
      avatarAlt: '管理员头像预览',
    },
    account: {
      title: '登录账号设置',
      subtitle: '可在这里更新登录用户名、邮箱和密码。',
      usernameLabel: '登录用户名',
      usernamePlaceholder: '请输入登录用户名',
      emailLabel: '登录邮箱',
      emailPlaceholder: '请输入登录邮箱',
      passwordLabel: '新密码',
      passwordPlaceholder: '留空则不修改密码',
      saveButton: '保存账号',
      savingButton: '保存中...',
      saveSuccess: '登录账号已更新',
      saveFailed: '更新登录账号失败，请稍后重试',
      emptyUsernameError: '登录用户名不能为空',
      emptyEmailError: '登录邮箱不能为空',
    },
  },
  footerManager: {
    page: {
      title: '页尾设置',
      subtitle: '在这里维护备案号与页尾自定义文案，保存后前台页面会同步使用。',
      metaTitle: '页尾设置 | Miku Blog',
      metaDescription: '后台页尾备案号与自定义文案设置',
    },
    form: {
      icpTitle: '备案信息',
      icpHint: '支持填写工信部备案号与备案查询地址。',
      icpLabel: '备案号',
      icpPlaceholder: '例如：沪ICP备12345678号-1',
      icpLinkLabel: '备案链接',
      icpLinkPlaceholder: '例如：https://beian.miit.gov.cn/',
      customTitle: '自定义文案',
      customHint: '可添加多行页尾说明文案，例如版权声明、联系方式或运营提示。',
      customLineLabelPrefix: '页尾文案第 ',
      customLinePlaceholder: '输入一行页尾文案',
      emptyCustomHint: '还没有自定义文案，点击“添加文案”即可新增。',
      addButton: '+ 添加文案',
      addButtonAria: '添加页尾文案',
      removeButton: '删除',
      removeButtonAria: '删除这条页尾文案',
      saveButton: '保存页尾配置',
      saveButtonAria: '保存页尾配置',
      savingButton: '保存中...',
      resetButton: '恢复默认',
      resetButtonAria: '恢复默认页尾配置',
    },
    toast: {
      saveSuccess: '页尾配置已保存',
      saveFailed: '页尾配置保存失败，请稍后重试',
      resetSuccess: '已恢复默认页尾配置',
    },
  },
  momentsManager: {
    profile: {
      title: '管理员说说身份',
      subtitle: '发布说说时会自动使用这里的昵称与头像。',
      displayNameLabel: '昵称',
      displayNamePlaceholder: '请输入展示昵称',
      avatarLabel: '头像 URL',
      avatarPlaceholder: '请输入头像链接，留空将使用默认头像',
      saveButton: '保存身份',
      savingButton: '保存中...',
      saveSuccess: '管理员身份已更新',
      saveFailed: '保存管理员身份失败，请稍后重试',
      emptyNameError: '昵称不能为空',
      avatarAlt: '管理员头像预览',
      autoHint: '发布说说时自动带入管理员昵称与头像',
    },
    account: {
      title: '登录账号设置',
      subtitle: '可在这里更新登录用户名、邮箱和密码。',
      usernameLabel: '登录用户名',
      usernamePlaceholder: '请输入登录用户名',
      emailLabel: '登录邮箱',
      emailPlaceholder: '请输入登录邮箱',
      passwordLabel: '新密码',
      passwordPlaceholder: '留空则不修改密码',
      saveButton: '保存账号',
      savingButton: '保存中...',
      saveSuccess: '登录账号已更新',
      saveFailed: '更新登录账号失败，请稍后重试',
      emptyUsernameError: '登录用户名不能为空',
      emptyEmailError: '登录邮箱不能为空',
    },
    actions: {
      deleteButton: '删除',
      deleteAria: '删除说说',
      deleteConfirm: '确认删除这条说说吗？删除后无法恢复。',
      deleteSuccess: '说说已删除',
      deleteFailed: '删除说说失败，请稍后重试',
    },
  },
}
