/**
 * DIY 文案入口（后台）
 *
 * 用法：
 * 1. 后台页面出现可见文案，优先放到这里再在组件中引用。
 * 2. 该文件是运营/设计同学改文案的首选入口，避免在多个 Vue 文件里到处找字符串。
 */

export const adminCopy = {
  layout: {
    defaultPageTitle: '仪表盘',
    page: {
      metaTitle: '后台管理 | Miku Blog',
      metaDescription: 'Miku Blog 后台管理中心',
    },
  },
  backup: {
    page: {
      metaTitle: '数据备份 | Miku Blog',
      metaDescription: '后台数据导出与备份',
    },
    title: '数据导出与备份',
    subtitle: '一键导出 JSON 或 SQL 备份，方便迁移与灾备。',
    jsonCardTitle: 'JSON 备份',
    jsonCardDescription: '导出结构化 JSON，适合审计与跨环境传输。',
    sqlCardTitle: 'SQL 备份',
    sqlCardDescription: '导出可直接回放的 SQL 脚本，适合完整恢复。',
    jsonButton: '导出 JSON',
    sqlButton: '导出 SQL',
    exporting: '导出中...',
    success: '备份导出成功',
    failed: '备份导出失败，请稍后重试',
  },
  moderation: {
    rateLimit: {
      title: 'Redis 限流观测',
      subtitle: '最近窗口的放行/拦截趋势与规则命中分布。',
      refresh: '刷新',
      loading: '加载中...',
      totalAllowed: '放行总数',
      totalBlocked: '拦截总数',
      ruleTitle: '规则命中',
      trendTitle: '分钟趋势',
      noData: '暂无限流数据',
      allowedLegend: '放行',
      blockedLegend: '拦截',
      ruleColumn: '规则',
      allowedColumn: '放行',
      blockedColumn: '拦截',
      totalColumn: '总计',
    },
  },
  loginForm: {
    page: {
      metaTitle: '登录 | Miku Blog',
      metaDescription: 'Miku Blog 后台登录入口',
    },
    hero: {
      consoleLabel: 'Miku Blog Console',
      title: '欢迎回来',
      subtitle: '仅管理员可访问后台系统',
    },
    quickLinks: [
      { href: '/blog', label: '博客首页', ariaLabel: '前往博客首页' },
      { href: '/guestbook', label: '留言板', ariaLabel: '前往留言板' },
      { href: '/friends', label: '友情链接', ariaLabel: '前往友链页面' },
    ],
    form: {
      identifierLabel: '用户名或邮箱',
      identifierPlaceholder: 'admin 或 admin@miku.blog',
      identifierAria: '用户名或邮箱',
      passwordLabel: '密码',
      passwordPlaceholder: '请输入密码',
      passwordAria: '密码',
      showPasswordAria: '显示密码',
      hidePasswordAria: '隐藏密码',
      submitButton: '登录',
      submittingButton: '登录中...',
      submitAria: '登录',
      submittingHint: '正在验证账号信息…',
      idleHint: '请使用有效管理员账号登录后台',
      emptyIdentifierError: '账号不能为空',
      emptyPasswordError: '密码不能为空',
      invalidCredentialsError: '账号或密码错误，请重新输入',
      successMessage: '登录成功，正在进入后台...',
      fallbackError: '登录失败，请稍后重试。',
    },
  },
  commentsManager: {
    page: {
      title: '评论审核',
      subtitle: '管理文章评论与留言板留言的审核队列。',
      metaTitle: '评论审核 | Miku Blog',
      metaDescription: '后台评论审核',
      pendingSuffix: ' 条待审核',
    },
    sourceTabs: {
      post: '文章评论',
      guestbook: '留言板留言',
    },
    table: {
      author: '评论者',
      content: '内容',
      source: '来源',
      status: '状态',
      createdAt: '提交时间',
      actions: '操作',
      empty: '暂无数据',
    },
    context: {
      anonymous: '匿名用户',
      secondaryFallback: '--',
      sourceFallback: '--',
      guestbookReply: '留言板回复',
      guestbookRoot: '留言板主留言',
      replyToPrefix: '回复 ',
      replyToFallback: '上一条留言',
      voteScorePrefix: '热度分 ',
    },
    buttons: {
      approve: '通过',
      reject: '驳回',
      delete: '删除',
      approveAria: '通过评论',
      rejectAria: '驳回评论',
      deleteAria: '删除评论',
      prev: '上一页',
      next: '下一页',
    },
    status: {
      approved: '已通过',
      rejected: '已驳回',
      pending: '待审核',
    },
    pagination: {
      prefix: '第 ',
      pageSeparator: ' / ',
      totalPrefix: ' 页，共 ',
      suffix: ' 条',
    },
    toasts: {
      missingGuestbookEndpoint: '后端缺少留言审核接口，请重启并更新 backend 服务',
      loadCommentsFailed: '加载评论列表失败',
      loadRateLimitFailed: '加载限流指标失败',
      approveSuccess: '评论已通过',
      rejectSuccess: '评论已驳回',
      deleteSuccess: '评论已删除',
      actionFailed: '操作失败',
      deleteFailed: '删除失败',
    },
  },
  dashboard: {
    toolbar: {
      filter: 'Filter',
      prevWindowAria: '上一时间窗口',
      nextWindowAria: '下一时间窗口',
      pathFilter: 'Path Filter',
      pathPlaceholder: '输入路径关键字',
    },
    sections: {
      trafficOverviewTitle: 'Traffic Overview',
      trafficOverviewSubtitle: 'Visitors 和 Views 的时间分布',
      recentActivitiesTitle: '近期事项',
      recentActivitiesSubtitle: '管理员最近操作记录',
      pages: 'Pages',
      sources: 'Sources',
      environment: 'Environment',
      location: 'Location',
      geoDistribution: 'Geo Distribution',
      byCountry: 'By Country',
      traffic: 'Traffic',
    },
    ranges: {
      h24: 'Last 24 hours',
      d7: 'Last 7 days',
      d30: 'Last 30 days',
    },
    tabs: {
      path: 'Path',
      entry: 'Entry',
      exit: 'Exit',
      referrers: 'Referrers',
      channels: 'Channels',
      browsers: 'Browsers',
      os: 'OS',
      devices: 'Devices',
      countries: 'Countries',
      regions: 'Regions',
      cities: 'Cities',
    },
    table: {
      path: 'Path',
      source: 'Source',
      name: 'Name',
      region: 'Region',
      visitors: 'Visitors',
      percent: '%',
    },
    stats: {
      visitors: 'Visitors',
      visits: 'Visits',
      views: 'Views',
      bounceRate: 'Bounce rate',
      visitDuration: 'Visit duration',
    },
    actions: {
      approve: '通过了',
      reject: '拒绝了',
      delete: '删除了',
      create: '创建了',
      update: '更新了',
      publish: '发布了',
      unpublish: '下架了',
      schedule: '定时发布了',
    },
    targets: {
      comment: '评论',
      post: '文章',
      friend_link: '友链',
      guestbook: '留言',
      moment: '说说',
    },
    notices: {
      pendingPrefix: '评论留言待审核：',
      pendingSuffix: ' 条',
      pendingSubtitle: '建议优先处理审核队列，避免积压',
      draftPrefix: '草稿待发布：',
      draftSuffix: ' 篇',
      draftSubtitle: '可前往文章管理检查内容后发布',
    },
    mapFallback: {
      loading: '世界地图加载中...',
      empty: '暂无国家分布数据',
      failed: '无法加载地图底图，已在下方显示国家排行',
    },
    common: {
      loading: '加载中...',
      emptyActivities: '暂无操作记录',
      operatorPrefix: '操作人：',
      activityTargetPrefix: '一条',
      unknown: 'Unknown',
      windowFallback: 'Window',
      less: 'Less',
      more: 'More',
      justNow: '刚刚',
      minutesAgo: '分钟前',
      hoursAgo: '小时前',
      daysAgo: '天前',
      noData: '--',
    },
    operations: {
      badge: 'Operations Cockpit',
      title: '运营驾驶舱',
      subtitle: '把内容表现、发布节奏、审核压力和依赖健康收拢到同一层视图，先补齐真正会影响日常运营决策的信息。',
      windowPrefix: '观察窗口',
      cards: {
        published: '在架内容',
        publishedHint: '非草稿文章总量，包含已发布与定时发布。',
        interactions: '互动沉淀',
        interactionsHint: '累计点赞与评论存量，可快速判断内容池沉淀程度。',
        reviewQueue: '审核队列',
        reviewQueueHint: '评论、留言与友链申请待处理总量。',
        dependencies: '依赖健康',
        dependenciesHint: 'GitHub、天气、GeoIP 与友链巡检可用性。',
      },
      alerts: {
        title: '异常提醒',
        stableTitle: '运行平稳',
        stableDetail: '当前没有明显积压或依赖异常，保持既有发布节奏即可。',
        trafficDropTitle: '访问波动偏大',
        trafficDropDetail: '当前窗口 Visitors 相比上一窗口明显回落，建议复查最近发布入口与首页曝光位。',
        reviewBacklogTitle: '审核积压上升',
        reviewBacklogDetail: '待审核项已进入需要关注的区间，建议优先处理评论、留言与友链申请。',
        draftStaleTitle: '草稿停留过久',
        draftStaleDetail: '存在超过两周未推进的草稿，建议尽快确认是否继续发布。',
        dependencyTitle: '外部依赖异常',
        dependencyDetail: 'GitHub、天气或友链巡检存在失败项，建议检查外部服务与缓存状态。',
      },
      performance: {
        title: '内容表现',
        subtitle: '按阅读、点赞、评论综合热度排序，帮助快速定位当前最值得继续放大的文章。',
        empty: '暂无文章数据',
        columnTitle: '文章',
        columnViews: 'PV',
        columnLikes: '点赞',
        columnComments: '评论',
        columnScore: '热度',
        recentBadge: '新发布',
      },
      rhythm: {
        title: '运营节奏',
        subtitle: '结合最近发布、定时队列、长期草稿与说说活跃度，判断内容推进是否顺畅。',
        recentTitle: '最近发布',
        queueTitle: '待推进队列',
        emptyRecent: '近期还没有已发布文章',
        emptyQueue: '当前没有定时文章或长期草稿',
        published7d: '近 7 天发文',
        scheduledPosts: '定时文章',
        scheduledMoments: '定时说说',
        staleDrafts: '长期草稿',
        activeMoments: '近 7 天说说',
        dueLabel: '排期',
        staleLabel: '已停留',
      },
      review: {
        title: '审核压力',
        subtitle: 'A 方案先聚焦待审核规模和最近处理动作，不引入额外迁移也能判断当前运营负载。',
        pendingComments: '待审评论',
        pendingGuestbook: '待审留言',
        pendingApplications: '待审友链',
        recentActions: '最近处理',
        empty: '最近没有审核动作',
        commentQueueHint: '文章评论等待处理',
        guestbookQueueHint: '留言板消息等待处理',
        friendQueueHint: '友链申请等待处理',
      },
      dependencies: {
        title: '依赖健康',
        subtitle: '统一查看 GitHub、天气、GeoIP 与友链巡检状态，同时确认首页顶部组件开关是否符合当前运营策略。',
        github: 'GitHub',
        weather: '天气',
        geoip: 'GeoIP',
        friends: '友链巡检',
        widgetsTitle: '首页组件开关',
        widgetsHint: '这些开关来自设置中心，会直接影响首页顶部天气、音乐和时钟模块。',
        widgetWeather: '天气',
        widgetMusic: '音乐',
        widgetClock: '时钟',
        stateHealthy: '正常',
        stateWarning: '关注',
        stateError: '异常',
        stateIdle: '未配置',
        stateDisabled: '已关闭',
        geoipHealthyDetail: '地域分布数据正常产出，可继续用于访问画像。',
        geoipWarningDetail: '当前窗口没有足够的地域分布数据，可能走了降级或样本不足。',
        friendsHealthyDetail: '友链巡检没有发现异常站点。',
        friendsWarningPrefix: '异常站点',
        friendsUnknownDetail: '暂未获取到友链巡检结果。',
        friendsDownDetail: '站点需要复查连通性。',
        friendsPendingDetail: '个站点待确认',
        githubMissing: '未配置 GitHub 用户名',
        githubReadableDetail: '个公开仓库可访问',
        githubOkDetail: 'GitHub 资料读取正常',
        githubErrorDetail: 'GitHub 资料拉取失败，请检查用户名、缓存或外部 API 可用性。',
        weatherDefault: '未设置后台地点，将使用后端默认位置。',
        weatherOkDetail: '天气服务读取正常',
        weatherErrorDetail: '天气服务读取失败，请检查外部网络或后端缓存状态。',
        defaultLocation: 'Default',
      },
      breakdown: {
        commentsStock: '累计评论',
        activeWidgets: '已启用组件',
        queueBreakdown: '队列拆分',
        recentOpsSuffix: '次',
        daysSuffix: '天',
        itemsSuffix: '项',
        postsSuffix: '篇',
        momentsSuffix: '条',
        dependenciesSuffix: '项正常',
        geoipNodesSuffix: '个地域节点',
        publishedStatus: '已发布',
        scheduledStatus: '排期',
        commentsShort: '评论',
        guestbookShort: '留言',
        friendsShort: '友链',
      },
    },
    degradedMessage: 'Analytics 数据暂不可用，当前显示占位数据。请先在 `backend` 目录执行 `go run cmd/migrate/main.go`。',
  },
  settingsCenter: {
    page: {
      title: '设置中心',
      subtitle: '把站点资料、首页首屏、页尾合规和管理员资料汇总到一个统一入口，减少分散维护。',
      metaTitle: '设置中心 | Miku Blog',
      metaDescription: '后台设置中心',
    },
    overview: {
      badge: 'Phase 5',
      title: '后台设置中心',
      description: '设置中心现已完成首页、作者资料、外部依赖、页尾与管理员账号的统一收口，并完成 fallback 治理与旧入口清理。',
      mergedLabel: '本次已并入',
      mergedItems: ['站点资料', '首页 Hero', '首页视觉资源', '作者展示', '外部依赖', '页尾与合规', '个人与账号'],
      fallbackLabel: '默认值回退',
      fallbackValue: 'copy/ 与现有 store',
    },
    sections: {
      navTitle: '配置分组',
      affectedLabel: '影响范围',
      pendingBadge: '未保存',
      siteProfile: {
        title: '站点资料',
        eyebrow: 'Brand / SEO',
        description: '统一维护品牌名称、站点标题、默认描述与默认分享图。',
        impact: ['前台导航', '页尾品牌', '默认 SEO', 'RSS 标题'],
        previewTitle: '站点资料预览',
        previewSubtitle: '模拟品牌与默认 SEO 在前台的表现。',
      },
      homeHero: {
        title: '首页 Hero',
        eyebrow: 'Home Hero',
        description: '维护首页首屏标题与副标题，让站点门面可以直接在后台调整。',
        impact: ['首页首屏', 'Hero 标题', '打字机副标题'],
        previewTitle: 'Hero 文案预览',
        previewSubtitle: '模拟首页首屏文案和打字机展示效果。',
      },
      homeAssets: {
        title: '首页视觉资源',
        eyebrow: 'Home Assets',
        description: '管理首页背景图列表与切换素材，保存后前台换图逻辑会立即使用新资源。',
        impact: ['首页背景', '换图按钮', '首屏氛围'],
        previewTitle: '视觉资源预览',
        previewSubtitle: '确认封面图顺序、数量与画面统一性。',
      },
      authorProfile: {
        title: '作者展示资料',
        eyebrow: 'Author Profile',
        description: '统一维护 Blog 侧栏、About 首屏和对外联系所使用的展示身份、简介和公开链接。',
        impact: ['Blog 侧栏', 'About 首屏', '联系方式区', '公开社交链接'],
        previewTitle: '作者资料预览',
        previewSubtitle: '从访客视角确认头像、身份、简介和标签是否统一。',
      },
      siteIntegrations: {
        title: '外部依赖与组件',
        eyebrow: 'Integrations',
        description: '维护 GitHub 用户名、天气地点与首页顶部小组件开关，并在后台查看依赖连通状态。',
        impact: ['About GitHub 卡片', '首页天气', '首页音乐', '首页时钟'],
        previewTitle: '依赖状态预览',
        previewSubtitle: '确认当前连接目标与首页顶部组件显隐策略。',
      },
      siteFooter: {
        title: '页尾与合规',
        eyebrow: 'Footer / Compliance',
        description: '集中管理备案信息与页尾说明文案，保证全站回退一致。',
        impact: ['全站页尾', '备案链接', '运营说明'],
        previewTitle: '页尾预览',
        previewSubtitle: '模拟前台页尾的最终展示顺序。',
      },
      adminProfile: {
        title: '个人与账号',
        eyebrow: 'Admin Identity',
        description: '维护后台身份、头像、登录用户名、邮箱与密码。',
        impact: ['后台头部', '管理员身份', '登录账号'],
        previewTitle: '管理员预览',
        previewSubtitle: '用于确认头像、昵称和账号信息是否统一。',
      },
    },
    preview: {
      panelTitle: '实时预览',
      boundaryTitle: '配置边界',
      boundaryDescription: '这里只放非敏感运营配置。Token、数据库凭证、JWT Secret 等仍通过环境变量管理。',
      impactTitle: '配置说明',
      impactDescription: '保存后会立即写回现有 store，并继续保留 `copy/` 作为默认回退。',
      heroBadge: 'HOME HERO',
      heroTitleLabel: '首屏标题',
      heroSubtitleLabel: '首屏副标题',
      heroImagesLabel: '封面资源',
      heroImageCountPrefix: '当前共 ',
      heroImageCountSuffix: ' 张',
      seoLabel: '默认标题',
      urlLabel: '站点域名',
      socialImageLabel: '默认分享图',
      footerLabel: '页尾文案',
      authorBioLabel: '博客简介',
      authorAboutLabel: 'About 简介',
      authorTagsLabel: '公开标签',
      authorSocialLabel: '公开链接',
      authorMetaLabel: '作者信息',
      authorNowLabel: '近况列表',
      githubStatusTitle: 'GitHub 连接',
      weatherStatusTitle: '天气服务',
      widgetStatusTitle: '首页组件开关',
      widgetOnLabel: '已显示',
      widgetOffLabel: '已隐藏',
      statusIdle: '未检查',
      statusLoading: '检查中',
      statusSuccess: '正常',
      statusError: '异常',
      accountLabel: '登录账号',
      avatarAlt: '管理员头像预览',
    },
    forms: {
      homeHero: {
        title: '首页首屏文案',
        subtitle: '用于首页正中央的标题与打字机副标题，建议保持短句和辨识度。',
        heroTitleLabel: 'Hero 标题',
        heroTitlePlaceholder: '例如：薰逸の猫窝',
        heroSubtitleLabel: 'Hero 副标题',
        heroSubtitlePlaceholder: '例如：「月が綺麗ですね, 風も優しいですね」。',
        validationRequired: '请至少填写首页 Hero 标题和副标题。',
      },
      homeAssets: {
        title: '首页背景图',
        subtitle: '支持相对路径或完整图片 URL。建议控制在 3 到 6 张，保证切换节奏稳定。',
        heroImageLabelPrefix: '封面图 ',
        heroImagePlaceholder: '例如：/picture/fengmian/1.webp',
        addButton: '+ 添加封面',
        addButtonAria: '添加首页封面图',
        removeButton: '删除',
        removeButtonAria: '删除这张首页封面图',
        emptyHint: '还没有首页封面图，至少添加一张后再保存。',
        validationRequired: '请至少保留一张有效的首页封面图。',
      },
      authorProfile: {
        title: '作者公开资料',
        subtitle: '用于访客可见的作者展示，不包含登录敏感信息。',
        basicsTitle: '基础信息',
        basicsSubtitle: '优先影响 Blog 侧栏与 About 首屏。',
        displayNameLabel: '展示名',
        displayNamePlaceholder: '例如：Xunyi',
        avatarLabel: '头像 URL',
        avatarPlaceholder: '例如：/picture/author.jpg',
        roleLabel: '角色标题',
        rolePlaceholder: '例如：Front-end Developer / Writer',
        locationLabel: '所在地',
        locationPlaceholder: '例如：China / Shanghai',
        sinceLabel: '起始时间',
        sincePlaceholder: '例如：Since 2026',
        contactEmailLabel: '联系邮箱',
        contactEmailPlaceholder: '例如：chw0536@126.com',
        bioLabel: 'Blog 简介',
        bioPlaceholder: '用于博客列表作者卡片的简介。',
        aboutDescriptionLabel: 'About 简介',
        aboutDescriptionPlaceholder: '用于 About 页面首屏描述。',
        quoteLabel: '个人引言',
        quotePlaceholder: '用于 About 页面右侧引用块。',
        skillsTitle: '公开标签',
        skillsSubtitle: '用于 Blog 侧栏标签与 About 首屏身份标签。',
        skillPlaceholder: '例如：Astro',
        addSkillButton: '+ 添加标签',
        addSkillButtonAria: '添加作者公开标签',
        nowTitle: '近况列表',
        nowSubtitle: '用于 Blog 侧栏和 About 右侧卡片。',
        nowPlaceholder: '例如：整理 Astro + Vue Islands 模板',
        addNowButton: '+ 添加近况',
        addNowButtonAria: '添加作者近况',
        socialTitle: '公开社交链接',
        socialSubtitle: '支持在 Blog 侧栏展示图标按钮。',
        socialLabelPlaceholder: '链接名称，例如 GitHub',
        socialHrefPlaceholder: '链接地址，例如 https://github.com/awkker',
        socialIconPlaceholder: '图标标识，例如 github / x / mail',
        addSocialButton: '+ 添加社交链接',
        addSocialButtonAria: '添加作者社交链接',
        contactLinksTitle: '联系扩展入口',
        contactLinksSubtitle: '用于 About 页面底部联系按钮。',
        contactLabelPlaceholder: '入口名称，例如 Bilibili',
        contactHrefPlaceholder: '入口地址，例如 https://space.bilibili.com/...',
        addContactButton: '+ 添加联系入口',
        addContactButtonAria: '添加作者联系入口',
        removeButton: '删除',
        removeButtonAria: '删除当前条目',
        emptySkillsHint: '还没有公开标签，建议至少保留 3 到 5 个核心方向。',
        emptyNowHint: '还没有近况条目，可以补充你最近在做的事情。',
        emptySocialHint: '还没有公开社交链接，至少添加一个主联系入口会更完整。',
        emptyContactHint: '还没有 About 联系入口，必要时可以只保留邮箱与 GitHub。',
        validationRequired: '请至少填写展示名、角色、Blog 简介和 About 简介。',
      },
      siteIntegrations: {
        title: '外部依赖与首页组件',
        subtitle: '这里控制公开依赖目标和首页顶部显示策略。',
        githubUsernameLabel: 'GitHub 用户名',
        githubUsernamePlaceholder: '例如：awkker',
        weatherLocationLabel: '天气地点',
        weatherLocationPlaceholder: '例如：Shanghai / Tokyo / Hangzhou',
        widgetsTitle: '首页顶部小组件',
        widgetsSubtitle: '控制音乐、天气、时钟在首页顶部是否显示。',
        showWeatherLabel: '显示天气',
        showWeatherHint: '首页顶部显示天气信息',
        showMusicLabel: '显示音乐播放器',
        showMusicHint: '首页顶部显示音乐播放器',
        showClockLabel: '显示系统时钟',
        showClockHint: '首页顶部显示时钟',
        statusTitle: '依赖状态检查',
        statusSubtitle: '使用当前表单中的 GitHub 用户名与天气地点做连通性检查。',
        refreshButton: '刷新状态',
        refreshingButton: '检查中...',
        githubMissingHint: '未填写 GitHub 用户名，About 页将回退到默认值或隐藏该模块。',
        weatherDefaultHint: '未填写天气地点时，将使用后端默认地点。',
      },
    },
    actions: {
      saveButton: '保存当前分组',
      savingButton: '保存中...',
      resetButton: '恢复默认',
      statusIdle: '选择分组后即可统一维护设置。',
      statusLoading: '正在加载设置中心配置...',
      statusPending: '当前分组存在未保存改动。',
      statusSavedPrefix: '最近保存',
      statusScopePrefix: '当前分组',
      emptyValue: '未填写',
    },
    toasts: {
      homeHeroSaved: '首页 Hero 文案已保存',
      homeHeroFailed: '首页 Hero 文案保存失败，请稍后重试',
      homeHeroReset: '已恢复默认首页 Hero 文案',
      homeAssetsSaved: '首页视觉资源已保存',
      homeAssetsFailed: '首页视觉资源保存失败，请稍后重试',
      homeAssetsReset: '已恢复默认首页视觉资源',
      authorProfileSaved: '作者展示资料已保存',
      authorProfileFailed: '作者展示资料保存失败，请稍后重试',
      authorProfileReset: '已恢复默认作者展示资料',
      siteIntegrationsSaved: '外部依赖与组件设置已保存',
      siteIntegrationsFailed: '外部依赖与组件设置保存失败，请稍后重试',
      siteIntegrationsReset: '已恢复默认外部依赖与组件设置',
      adminSectionSaved: '个人与账号设置已更新',
      adminSectionFailed: '个人与账号设置更新失败，请稍后重试',
    },
  },
  profileManager: {
    page: {
      title: '个人设置',
      subtitle: '在这里统一维护后台身份与登录账号信息。',
      metaTitle: '个人设置 | Miku Blog',
      metaDescription: '后台个人设置',
    },
    profile: {
      title: '展示身份',
      subtitle: '文章、说说、关于页与博客列表将自动同步这里的昵称和头像。',
      displayNameLabel: '昵称',
      displayNamePlaceholder: '请输入展示昵称',
      avatarLabel: '头像 URL',
      avatarPlaceholder: '请输入头像链接，留空将使用默认头像',
      saveButton: '保存身份',
      savingButton: '保存中...',
      saveSuccess: '管理员身份已更新',
      saveFailed: '保存管理员身份失败，请稍后重试',
      emptyNameError: '昵称不能为空',
      avatarAlt: '管理员头像预览',
    },
    account: {
      title: '登录账号设置',
      subtitle: '可在这里更新登录用户名、邮箱和密码。',
      usernameLabel: '登录用户名',
      usernamePlaceholder: '请输入登录用户名',
      emailLabel: '登录邮箱',
      emailPlaceholder: '请输入登录邮箱',
      passwordLabel: '新密码',
      passwordPlaceholder: '留空则不修改密码',
      saveButton: '保存账号',
      savingButton: '保存中...',
      saveSuccess: '登录账号已更新',
      sessionRevokedSuccess: '登录账号已更新，请重新登录后台',
      saveFailed: '更新登录账号失败，请稍后重试',
      emptyUsernameError: '登录用户名不能为空',
      emptyEmailError: '登录邮箱不能为空',
    },
  },
  footerManager: {
    page: {
      title: '页尾与站点设置',
      subtitle: '在这里统一维护站点品牌、默认 SEO 与页尾文案，保存后前台页面会同步使用。',
      metaTitle: '页尾与站点设置 | Miku Blog',
      metaDescription: '后台站点品牌、默认 SEO 与页尾设置',
    },
    siteProfile: {
      title: '站点品牌与默认 SEO',
      subtitle: '这里维护运行时品牌显示、默认标题后缀、默认描述与分享图，前台会优先读取这里的真实配置。',
      brandTitle: '品牌信息',
      brandHint: '用于导航栏、页尾与运行时品牌展示同步。',
      brandTextLabel: '品牌展示名',
      brandTextPlaceholder: '例如：NanaMiku Blog',
      siteTitleLabel: '站点标题',
      siteTitlePlaceholder: '用于标题后缀、RSS 与默认 SEO 口径',
      logoAltLabel: 'Logo Alt 文案',
      logoAltPlaceholder: '例如：NanaMiku Blog logo',
      seoTitle: '默认 SEO',
      seoHint: '用于 canonical 基准、默认描述与默认分享图回退。',
      siteUrlLabel: '站点 URL',
      siteUrlPlaceholder: '例如：https://nanamiku.blog',
      defaultDescriptionLabel: '默认描述',
      defaultDescriptionPlaceholder: '请输入站点默认 SEO 描述',
      defaultSocialImageLabel: '默认分享图',
      defaultSocialImagePlaceholder: '支持相对路径或完整图片 URL',
      saveButton: '保存站点配置',
      saveButtonAria: '保存站点品牌与默认 SEO 配置',
      savingButton: '保存中...',
      resetButton: '恢复默认站点配置',
      resetButtonAria: '恢复默认站点品牌与默认 SEO 配置',
      validationRequired: '请至少填写品牌展示名、站点标题、站点 URL、默认描述和默认分享图。',
    },
    form: {
      icpTitle: '备案信息',
      icpHint: '如暂未备案可留空；已备案时再填写备案号与备案查询地址。',
      icpLabel: '备案号',
      icpPlaceholder: '暂未备案可留空',
      icpLinkLabel: '备案链接',
      icpLinkPlaceholder: '已备案时再填写查询链接',
      customTitle: '自定义文案',
      customHint: '可添加多行页尾说明文案，例如版权声明、联系方式或运营提示。',
      customLineLabelPrefix: '页尾文案第 ',
      customLinePlaceholder: '输入一行页尾文案',
      emptyCustomHint: '还没有自定义文案，点击“添加文案”即可新增。',
      addButton: '+ 添加文案',
      addButtonAria: '添加页尾文案',
      removeButton: '删除',
      removeButtonAria: '删除这条页尾文案',
      saveButton: '保存页尾配置',
      saveButtonAria: '保存页尾配置',
      savingButton: '保存中...',
      resetButton: '恢复默认',
      resetButtonAria: '恢复默认页尾配置',
    },
    toast: {
      saveSuccess: '页尾配置已保存',
      saveFailed: '页尾配置保存失败，请稍后重试',
      resetSuccess: '已恢复默认页尾配置',
    },
    siteProfileToast: {
      saveSuccess: '站点品牌与默认 SEO 已保存',
      saveFailed: '站点品牌与默认 SEO 保存失败，请稍后重试',
      resetSuccess: '已恢复默认站点品牌与默认 SEO 配置',
    },
  },
  friendsManager: {
    page: {
      title: '友链管理',
      subtitle: '维护友链展示、申请审核和站点健康检查。',
      metaTitle: '友链管理 | Miku Blog',
      metaDescription: '后台友链管理',
      addButton: '+ 添加友链',
      addButtonAria: '添加友链',
    },
    forms: {
      createTitle: '添加友链',
      editTitle: '编辑友链',
      namePlaceholder: '站点名称 *',
      urlPlaceholder: '站点 URL *',
      avatarPlaceholder: '头像 URL',
      descriptionPlaceholder: '站点描述',
      sortPlaceholder: '排序值（越小越靠前）',
      createButton: '添加友链',
      creatingButton: '添加中...',
      updateButton: '保存修改',
      updatingButton: '保存中...',
      cancelButton: '取消',
    },
    stats: {
      approved: '已通过',
      pending: '待审核',
      down: '异常 / 不可达',
    },
    applications: {
      title: '申请队列',
      subtitle: '前台提交的友链申请会进入这里，审核通过后自动转为正式友链。',
      empty: '暂时没有友链申请',
      columns: {
        site: '站点',
        contact: '联系信息',
        description: '说明',
        status: '状态',
        createdAt: '提交时间',
        actions: '操作',
      },
      approveButton: '通过',
      rejectButton: '拒绝',
      processingButton: '处理中...',
      reviewedPrefix: '审核时间：',
      notePrefix: '备注：',
    },
    links: {
      tableTitle: '正式友链',
      empty: '还没有友链记录',
      columns: {
        name: '站点名称',
        url: '链接',
        status: '状态',
        health: '健康检测',
        createdAt: '添加时间',
        actions: '操作',
      },
      approveButton: '通过',
      rejectButton: '拒绝',
      editButton: '编辑',
      deleteButton: '删除',
      healthOk: '正常',
      healthDown: '不可达',
    },
    status: {
      approved: '已通过',
      pending: '待审核',
      rejected: '已拒绝',
    },
    toasts: {
      loadFriendsFailed: '加载友链列表失败',
      loadApplicationsFailed: '加载申请列表失败',
      createSuccess: '友链添加成功',
      createFailed: '添加友链失败',
      updateSuccess: '友链更新成功',
      updateFailed: '更新友链失败',
      deleteSuccess: '友链已删除',
      deleteFailed: '删除失败',
      approveFriendSuccess: '友链已通过',
      rejectFriendSuccess: '友链已拒绝',
      approveApplicationSuccess: '申请已通过并转为正式友链',
      rejectApplicationSuccess: '申请已拒绝',
    },
  },
  postsManager: {
    page: {
      metaTitle: '文章管理 | Miku Blog',
      metaDescription: '后台文章管理',
    },
    header: {
      title: '文章管理',
      subtitle: '管理博客文章的发布、草稿与分类。',
    },
    createButton: '+ 新建文章',
    createForm: {
      titlePlaceholder: '无题...',
      newBadge: '新文章',
      editingBadge: '编辑中',
      metaToggle: '文章属性',
      categoryLabel: '分类',
      categoryPlaceholder: '技术 / 随笔 / 教程',
      tagsLabel: '标签',
      tagsPlaceholder: '用逗号分隔',
      excerptLabel: '摘要',
      excerptPlaceholder: '简短描述文章内容',
      heroImageLabel: '封面图片',
      heroImagePlaceholder: 'https://...',
      contentPlaceholder: '在此撰写你的想法...',
      statusDraft: '草稿',
      statusPublished: '直接发布',
      statusScheduled: '定时发布',
      cancelButton: '取消',
      createIdle: '创建文章',
      createLoading: '创建中...',
      saveIdle: '保存修改',
      saveLoading: '保存中...',
    },
    charUnit: ' 字',
    charTenThousandUnit: ' 万字',
    table: {
      colTitle: '标题',
      colCategory: '分类',
      colStatus: '状态',
      colViews: '浏览量',
      colPublishTime: '发布时间/计划时间',
      colActions: '操作',
      emptyMessage: '尚无文章',
      firstPostCta: '撰写第一篇',
    },
    actions: {
      editAria: '编辑文章',
      editButton: '编辑',
      publishAria: '发布文章',
      publishButton: '发布',
      scheduleAria: '定时发布文章',
      scheduleButton: '定时',
      schedulePrompt: '请输入计划发布时间（格式：YYYY-MM-DDTHH:mm）',
      unpublishAria: '转为草稿',
      unpublishButton: '转草稿',
      deleteAria: '删除文章',
      deleteButton: '删除',
    },
    status: {
      published: '已发布',
      draft: '草稿',
      scheduled: '定时发布',
    },
    toast: {
      loadFailed: '加载文章列表失败',
      createSuccess: '文章创建成功',
      createFailed: '创建文章失败，请稍后重试',
      loadDetailFailed: '加载文章详情失败',
      updateSuccess: '文章更新成功',
      updateFailed: '更新文章失败，请稍后重试',
      publishSuccess: '文章发布成功',
      publishFailed: '发布失败，请稍后重试',
      scheduleSuccess: '文章已设为定时发布',
      scheduleFailed: '定时发布设置失败，请稍后重试',
      unpublishSuccess: '文章已转为草稿',
      unpublishFailed: '转草稿失败，请稍后重试',
      deleteSuccess: '文章已删除',
      deleteFailed: '删除失败，请稍后重试',
      scheduledAtRequired: '请选择定时发布时间',
    },
    charCount: {
      zero: '0 字',
      suffix: ' 字',
      tenThousandSuffix: ' 万字',
    },
  },
  momentsManager: {
    page: {
      metaTitle: '说说管理 | Miku Blog',
      metaDescription: '后台说说管理',
    },
    header: {
      title: '说说管理',
      subtitle: '发布和管理说说动态。',
    },
    createButton: '+ 发布说说',
    createForm: {
      contentPlaceholder: '此刻的想法...',
      editingBadge: '编辑中',
      metaToggle: '发布设置',
      statusLabel: '发布状态',
      statusDraft: '草稿',
      statusPublished: '立即发布',
      statusScheduled: '定时发布',
      scheduledLabel: '发布时间',
      imageLabel: '图片',
      imagePlaceholder: '贴入图片链接, 用逗号分隔 (最多4张)',
      cancelButton: '取消',
      publishIdle: '发布说说',
      publishLoading: '发布中...',
      saveIdle: '保存修改',
      saveLoading: '保存中...',
    },
    charUnit: ' 字',
    stats: {
      totalLabel: '说说总数',
      likesLabel: '总点赞',
      commentsLabel: '总评论',
    },
    list: {
      emptyMessage: '暂无说说',
      firstMomentCta: '发布第一条',
    },
    status: {
      published: '已发布',
      draft: '草稿',
      scheduled: '定时发布',
    },
    listActions: {
      editAria: '编辑说说',
      editButton: '编辑',
      publishAria: '发布说说',
      publishButton: '发布',
      scheduleAria: '定时发布说说',
      scheduleButton: '定时',
      schedulePrompt: '请输入计划发布时间（格式：YYYY-MM-DDTHH:mm）',
      unpublishAria: '转为草稿',
      unpublishButton: '转草稿',
    },
    toast: {
      loadFailed: '加载说说列表失败',
      createSuccess: '说说发布成功',
      createFailed: '发布说说失败，请稍后重试',
      updateSuccess: '说说更新成功',
      updateFailed: '更新说说失败，请稍后重试',
      publishSuccess: '说说发布成功',
      publishFailed: '发布失败，请稍后重试',
      scheduleSuccess: '说说已设为定时发布',
      scheduleFailed: '定时发布设置失败，请稍后重试',
      unpublishSuccess: '说说已转为草稿',
      unpublishFailed: '转草稿失败，请稍后重试',
      scheduledAtRequired: '请选择定时发布时间',
    },
    profile: {
      title: '管理员说说身份',
      subtitle: '发布说说时会自动使用这里的昵称与头像。',
      displayNameLabel: '昵称',
      displayNamePlaceholder: '请输入展示昵称',
      avatarLabel: '头像 URL',
      avatarPlaceholder: '请输入头像链接，留空将使用默认头像',
      saveButton: '保存身份',
      savingButton: '保存中...',
      saveSuccess: '管理员身份已更新',
      saveFailed: '保存管理员身份失败，请稍后重试',
      emptyNameError: '昵称不能为空',
      avatarAlt: '管理员头像预览',
      autoHint: '发布说说时自动带入管理员昵称与头像',
    },
    account: {
      title: '登录账号设置',
      subtitle: '可在这里更新登录用户名、邮箱和密码。',
      usernameLabel: '登录用户名',
      usernamePlaceholder: '请输入登录用户名',
      emailLabel: '登录邮箱',
      emailPlaceholder: '请输入登录邮箱',
      passwordLabel: '新密码',
      passwordPlaceholder: '留空则不修改密码',
      saveButton: '保存账号',
      savingButton: '保存中...',
      saveSuccess: '登录账号已更新',
      saveFailed: '更新登录账号失败，请稍后重试',
      emptyUsernameError: '登录用户名不能为空',
      emptyEmailError: '登录邮箱不能为空',
    },
    actions: {
      deleteButton: '删除',
      deleteAria: '删除说说',
      deleteConfirm: '确认删除这条说说吗？删除后无法恢复。',
      deleteSuccess: '说说已删除',
      deleteFailed: '删除说说失败，请稍后重试',
    },
    charCount: {
      zero: '0 字',
      suffix: ' 字',
    },
  },
  sidebar: {
    sections: {
      overview: 'OVERVIEW',
      content: 'CONTENT',
      settings: 'SETTINGS',
      system: 'SYSTEM',
    },
    nav: {
      dashboard: '仪表盘',
      posts: '文章管理',
      moments: '说说管理',
      comments: '评论审核',
      settingsCenter: '设置中心',
      footer: '页尾设置',
      profile: '个人设置',
      friends: '友链管理',
      backup: '数据备份',
    },
    footer: {
      home: '前台首页',
      homeAria: '前台首页',
      logout: '退出登录',
      logoutAria: '退出登录',
    },
    mobile: {
      brandTitle: 'Nanamiku Admin',
      closeAria: '关闭导航菜单',
    },
  },
  topbar: {
    openMenuAria: '打开导航菜单',
    breadcrumbAria: '面包屑导航',
    breadcrumbPrefix: 'Nanamiku Admin',
    homeLink: '前台首页',
    homeLinkAria: '前往前台首页',
    roleLabel: '管理员',
    logoutButton: '退出',
    logoutAria: '退出登录',
    defaultPageTitle: '仪表盘',
  },
  contentHeader: {
    openMenuAria: '打开导航菜单',
    roleLabel: '管理员',
    defaultPageTitle: '仪表盘',
  },
  sectionPlaceholder: {
    posts: [
      { title: '文章列表', desc: '后续接入发布状态、分类筛选和全文检索。' },
      { title: '草稿箱', desc: '支持草稿保存、自动恢复与版本记录。' },
      { title: '发布计划', desc: '预留定时发布与回滚入口。' },
    ],
    comments: [
      { title: '待审核评论', desc: '支持批量通过、驳回与敏感词标记。' },
      { title: '举报处理', desc: '统一管理用户举报与风险内容。' },
      { title: '黑名单策略', desc: '预留 IP/关键词规则配置面板。' },
    ],
    friends: [
      { title: '友链列表', desc: '维护已通过友链与展示排序。' },
      { title: '申请队列', desc: '集中处理交换申请与状态通知。' },
      { title: '校验任务', desc: '定期检测友链可用性与内容质量。' },
    ],
  },
  dashboardChart: {
    defaultTitle: '近 7 日趋势',
    loading: '加载中...',
  },
}
