/**
 * DIY 文案入口（站点级）
 *
 * 用法：
 * 1. 修改本文件即可调整首页 Dock、博客/说说/留言板/关于我/404 页面与其核心组件文案。
 * 2. 新页面需要可配置文案时，优先在本文件新增字段，再由页面读取，不要直接写死在组件模板里。
 */

export interface SiteNavItem {
  href: string
  label: string
  auth?: 'authed' | 'guest'
}

export interface HomeDockItem extends SiteNavItem {
  icon: string
  name: string
}

export interface SiteActionItem {
  href: string
  label: string
  ariaLabel: string
}

export const siteCopy = {
  brand: {
    logoAlt: 'NanaMiku Blog logo',
    text: 'NanaMiku Blog',
  },
  seo: {
    // DIY 入口：统一维护站点域名、品牌名、默认 SEO 描述与默认分享图。
    siteUrl: 'https://example.com',
    siteTitle: 'NanaMiku Blog',
    defaultDescription: '一个基于 Astro、Vue Islands 与 Go 的亮色液态玻璃博客模板，用于快速搭建个人内容站。',
    defaultSocialImage: '/picture/logo-64.webp',
  },
  common: {
    backToTopAria: '返回顶部',
  },
  siteFooter: {
    // DIY 入口：站点页尾备案号与自定义文案。默认值用于首次加载与“恢复默认”。
    defaults: {
      icpText: '',
      icpLink: '',
      customTexts: ['本站内容仅用于学习交流，请勿用于商业转载。'],
    },
    display: {
      copyrightPrefix: '© ',
      siteName: 'NANAMIKU BLOG',
      rightsText: '保留所有权利',
      icpAriaPrefix: '打开备案信息：',
    },
  },
  home: {
    metaTitle: 'nanamiku blog',
    metaDescription: 'nanamiku blog 开屏页',
    heroTitle: '创作入口',
    heroSubtitle: '把写作、作品与公开资料收拢到同一站点。',
    // DIY 入口：首页轮播背景图。可按需增删顺序，建议使用 `public/` 下的静态路径。
    heroImages: [
      '/picture/fengmian/1.webp',
      '/picture/fengmian/2.webp',
      '/picture/fengmian/3.webp',
    ],
    dockItems: [
      { name: '访客', href: '/about', icon: 'person' },
      { name: '博客', href: '/blog', icon: 'book' },
      { name: '说说', href: '/moments', icon: 'moments' },
      { name: '留言', href: '/guestbook', icon: 'message' },
      { name: '友链', href: '/friends', icon: 'link' },
      { name: '登录', href: '/login', icon: 'login', auth: 'guest' },
      { name: '后台', href: '/admin', icon: 'admin', auth: 'authed' },
    ] as HomeDockItem[],
  },
  blogTopNav: {
    ariaPrefix: '前往',
    mobileMenu: {
      panelAria: '移动端页面导航',
      openButtonAria: '打开导航菜单',
      closeButtonAria: '关闭导航菜单',
    },
    themeToggle: {
      switchToNightAria: '切换夜间模式',
      switchToLightAria: '切换亮色模式',
      nightLabel: '夜间',
      lightLabel: '亮色',
    },
    primaryLinks: [
      { href: '/blog', label: '博客首页' },
      { href: '/moments', label: '说说' },
      { href: '/guestbook', label: '留言板' },
      { href: '/friends', label: '友情链接' },
      { href: '/about', label: '关于' },
    ] as SiteNavItem[],
    actionLinks: [
      { href: '/admin', label: '后台', auth: 'authed' },
      { href: '/login', label: '登录', auth: 'guest' },
    ] as SiteNavItem[],
  },
  blogIndex: {
    metaTitle: 'Miku Blog',
    metaDescription: '博客主页',
    heroBadge: 'CREATOR SPACE',
    heroTitle: 'NanaMiku Blog',
    heroDescription: '这是一套面向内容创作者的博客模板，默认聚焦 Astro、Vue Islands 与 Go 的全栈实践展示。',
    heroActions: [
      { href: '#latest-posts', label: '看最新文章' },
      { href: '#archive', label: '进入归档' },
      { href: '/about', label: '关于我' },
    ],
    quickStats: [
      { label: '模板栈', value: 'Astro + Vue + Go + PostgreSQL' },
      { label: '默认主线', value: '公开资料收口与可配置化' },
      { label: '演示项目', value: 'Open Source Profile Release' },
    ],
    focusCard: {
      badge: '本月在做什么',
      title: '把博客整理成可开箱使用的创作者模板',
      description: '重点在信息分层、阅读引导与配置收口，让新访客快速知道这个站点展示什么、如何开始浏览。',
      footnote: '文章来自后台管理面板发布',
    },
    scrollCue: {
      label: '向下阅读',
      ariaLabel: '向下阅读',
    },
    authorCard: {
      avatarAlt: '博主头像',
      name: 'Your Name',
      role: 'Frontend / Full-stack Creator',
      bio: '在这里展示你的文章、作品与正在推进的主线，让访客快速建立对站点的第一印象。',
      location: 'Your City',
      since: 'Since 2026',
      skills: ['Astro', 'Vue', 'Go', 'TypeScript', 'Tailwind'],
      aboutCta: '查看完整个人介绍',
    },
    socialLinks: [
      {
        label: 'GitHub',
        href: 'https://github.com/yourname',
        icon: 'M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 00-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0020 4.77 5.07 5.07 0 0019.91 1S18.73.65 16 2.48a13.38 13.38 0 00-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 005 4.77a5.44 5.44 0 00-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 009 18.13V22',
      },
      {
        label: 'X',
        href: 'https://x.com/yourhandle',
        icon: 'M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z',
      },
      {
        label: 'Mail',
        href: 'mailto:hello@example.com',
        icon: 'M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2zm16 2l-8 5-8-5',
      },
    ],
    nowTitle: 'Now / 近况',
    nowItems: ['整理公开资料默认值', '补齐 DIY 配置入口', '检查亮色站点的阅读路径'],
    playlistTitle: '正在听',
    playlist: ['Lo-fi Focus Mix', 'Ambient Writing Session', 'City Pop Evening Mix'],
    backToTopAria: '返回顶部',
  },
  momentsPage: {
    metaTitle: '说说 | Miku Blog',
    metaDescription: 'Miku Blog 说说动态',
    heroBadge: 'MOMENTS',
    title: '说说',
    description: '碎片化的日常记录。随想、随拍、随心。',
    navAria: '页面导航',
    quickLinks: [
      { href: '/blog', label: '博客首页', ariaLabel: '前往博客首页' },
      { href: '/guestbook', label: '留言板', ariaLabel: '前往留言板' },
      { href: '/friends', label: '友情链接', ariaLabel: '前往友情链接' },
    ],
  },
  guestbookPage: {
    metaTitle: '留言板 | Miku Blog',
    metaDescription: 'Miku Blog 访客留言板',
    heroBadge: 'GUESTBOOK',
    title: '访客留言板',
    description: '这里是站点的公共交流区。欢迎留下你的想法、建议或一句路过打卡。',
    navAria: '页面导航',
    quickLinks: [
      { href: '/blog', label: '博客首页', ariaLabel: '前往博客首页' },
      { href: '/friends', label: '友情链接', ariaLabel: '前往友情链接页面' },
    ],
  },
  friendsPage: {
    metaTitle: '友情链接 | Miku Blog',
    metaDescription: 'Miku Blog 友情链接页面',
    heroBadge: 'FRIENDS',
    title: '友情链接',
    description: '欢迎和本站交换友链。请保持站点长期可访问，内容积极、持续更新。',
    navAria: '页面导航',
    quickLinks: [
      { href: '/blog', label: '博客首页', ariaLabel: '前往博客首页' },
      { href: '/guestbook', label: '留言板', ariaLabel: '前往留言板' },
    ],
    siteCard: {
      avatarAlt: '站点默认头像',
      title: 'NanaMiku Blog',
      badge: '本站',
      description: '一个可继续 DIY 的亮色博客模板，用来承载文章、作品与公开资料。',
      domain: 'example.com',
      requirement: '若希望交换，请先添加本站链接',
    },
    grid: {
      title: '友链墙',
      buildingStatus: '正在建设中',
      countPrefix: '已收录 ',
      countSuffix: ' 个站点',
      applyButton: '申请交换',
      closeButton: '收起表单',
      applyButtonAria: '申请交换友链',
      form: {
        title: '提交友链申请',
        description: '填写站点信息后会进入后台审核队列，审核通过后展示在友链墙。',
        siteNameLabel: '站点名称',
        siteNamePlaceholder: '例如：Example Studio',
        siteUrlLabel: '站点地址',
        siteUrlPlaceholder: '支持直接填写域名或完整 URL',
        avatarUrlLabel: '头像地址',
        avatarUrlPlaceholder: '可选，建议使用正方形 Logo',
        descriptionLabel: '站点简介',
        descriptionPlaceholder: '简要介绍站点方向、更新频率或内容气质',
        contactEmailLabel: '联系邮箱',
        contactEmailPlaceholder: '用于友链审核与联系沟通',
        contactNoteLabel: '补充说明',
        contactNotePlaceholder: '可补充已添加本站链接、推荐访问路径等信息',
        submitButton: '提交申请',
        submittingButton: '提交中...',
        cancelButton: '取消',
        footnote: '提交后会进入后台审核队列；如信息有更新，可以再次提交最新版本。',
      },
      validationRequired: '请至少填写站点名称、站点地址、站点简介和联系邮箱。',
      errorFallback: '友链读取失败，请稍后重试。',
      emptyTitle: '暂无友链',
      emptyDescription: '友链墙正在建设中，欢迎稍后再来。',
      applySuccess: '友链申请已提交，审核通过后会出现在友链墙。',
      applyDuplicate: '该站点已存在友链记录，或已有待审核申请。',
      applyFailed: '友链申请提交失败，请稍后重试。',
    },
  },
  aboutPage: {
    metaTitle: '关于我 | Miku Blog',
    metaDescription: 'NanaMiku Blog 的作者介绍与创作地图模板',
    heroBadge: 'ABOUT CREATOR',
    heroTitle: '我是 Your Name',
    heroDescription: '这里展示一位内容创作者的公开资料模板。你可以把简介、方向、项目与联系入口替换成自己的版本。',
    identityTags: ['Astro', 'Vue Islands', 'Go', 'Tailwind', 'Nano Stores'],
    heroActions: [
      { href: '/blog#latest-posts', label: '看精选文章' },
      { href: '#projects', label: '看主推项目' },
      { href: '', label: '联系我' },
    ],
    stats: {
      postsLabel: '已发布文章',
      focusLabel: '写作主线',
      focusValue: '前端体验 + 全栈实战',
      statusLabel: '当前状态',
      statusValue: '持续迭代中',
    },
    profileCard: {
      avatarAlt: '作者头像',
      name: 'Your Name',
      role: 'Frontend / Full-stack Creator',
      nowTitle: 'NOW / 近况',
      quote: '把每次写作、发布与配置，都整理成下一次还能继续复用的结构。',
    },
    nowItems: [
      '整理开源前默认值与示例值',
      '补充 About 页的可维护资料结构',
      '继续打磨 Astro + Vue Islands 的协作方式',
    ],
    introCards: [
      {
        title: '我在做什么',
        description: '把站点默认值、运行时配置和页面骨架分清楚，让博客既能直接运行，也容易继续 DIY。',
      },
      {
        title: '我为什么写作',
        description: '写作是整理方法和输出观点的过程，目标是让每篇内容都能支持真实项目落地。',
      },
      {
        title: '我关心的问题',
        description: '信息层次是否清晰、默认值是否安全、组件是否可复用、系统是否能长期迭代。',
      },
    ],
    timeline: {
      title: '成长时间线',
      subtitle: '从写作到全栈，再到创作者空间化。',
      resultPrefix: '结果：',
    },
    milestones: [
      {
        year: '2024',
        title: '开始系统写作',
        summary: '从零散笔记转向结构化输出，建立个人技术写作节奏。',
        result: '累计产出 20+ 篇可复用实践文章',
      },
      {
        year: '2025',
        title: '聚焦前端工程化',
        summary: '主攻组件复用、样式规范与协作流程，减少重复开发。',
        result: '沉淀多套前端页面模板与规范',
      },
      {
        year: '2025',
        title: '全栈化推进',
        summary: '将前端体验与 Go 后端能力联动，关注性能与可维护性。',
        result: '形成 Astro + Go 的完整博客技术路线',
      },
      {
        year: '2026',
        title: '创作者空间升级',
        summary: '把博客从文章列表升级为有路径、有节奏的创作者入口。',
        result: '上线 About / Blog 的新信息架构',
      },
    ],
    capabilityGroups: [
      {
        title: '前端体验',
        desc: '关注视觉层次、交互节奏与页面信息密度。',
        stack: ['Astro', 'Vue 3', 'Tailwind CSS', '组件化设计'],
      },
      {
        title: '工程化',
        desc: '用规范和流程提升迭代效率与可维护性。',
        stack: ['TypeScript', '模块化结构', '内容驱动页面', '性能优化'],
      },
      {
        title: '后端协同',
        desc: '强调接口稳定性、数据组织和全栈落地能力。',
        stack: ['Go', 'Hertz', 'sqlc', 'PostgreSQL / Redis'],
      },
    ],
    projectsSection: {
      title: '主推项目',
      subtitle: '我最希望访客优先进入的 3 条路径。',
      cta: '查看详情',
    },
    featuredProjects: [
      {
        name: 'Starter Site Kit',
        focus: 'Astro + Go 的亮色博客模板基座',
        role: '负责默认配置、公开资料治理与页面骨架搭建',
        metric: '让新仓库在未填后台配置时也能安全上线',
        href: 'https://github.com/yourname/miku-blog-starter',
      },
      {
        name: 'Glass UI Pack',
        focus: '液态玻璃 UI 组件与页面模块实验集',
        role: '负责组件 API 设计与亮色视觉统一策略',
        metric: '形成可复用卡片、面板与信息块模式',
        href: '/blog',
      },
      {
        name: 'Content Workflow Notes',
        focus: '围绕内容发布与公开资料维护的协作范式',
        role: '负责状态拆分、默认回退和设置中心接入策略',
        metric: '减少模板二次 DIY 时的重复改动成本',
        href: '/blog',
      },
    ],
    writingMapSection: {
      title: '写作地图',
      subtitle: '如果你是第一次来，可以这样阅读。',
      pathPrefix: 'PATH',
      cta: '进入',
    },
    writingMap: [
      {
        title: '入门先看',
        desc: '先从精选文章了解我最核心的技术观点与实现方式。',
        href: '/blog#latest-posts',
      },
      {
        title: '系列专栏',
        desc: '按专题连续阅读，适合系统学习同一方向。',
        href: '/blog#archive',
      },
      {
        title: '最近更新',
        desc: '快速查看我当前在推进的主线和近期输出。',
        href: '/blog#recent-updates',
      },
    ],
    monthlyGoalsTitle: '本月目标',
    monthlyGoals: ['补齐公开资料配置', '完善项目展示卡片', '检查移动端阅读体验'],
    listeningTitle: '正在听',
    listeningNow: ['Lo-fi Focus Mix', 'Ambient Writing Session', 'Late Night City Pop'],
    signature: {
      title: '固定签名',
      description: '技术不是为了堆砌概念，而是为了让内容组织更清晰、让协作与维护更顺畅。',
      footer: '愿每次更新都让这个模板更接近可长期维护的状态。',
    },
    contactSection: {
      title: '如果你也在做类似方向，欢迎交流',
      subtitle: '可以聊前端体验、工程化方案、站点搭建与公开资料治理。',
      emailButton: '发邮件',
      emailHref: '',
      githubButton: 'GitHub',
    },
    githubUsername: '',
    socialLinks: [
      { label: '作品集', href: 'https://example.com/portfolio' },
      { label: '联系页', href: 'https://example.com/contact' },
      { label: 'RSS', href: 'https://example.com/rss' },
    ],
    backToTopAria: '返回顶部',
  },
  notFoundPage: {
    metaTitle: '404 | Miku Blog',
    metaDescription: '页面不存在或已迁移',
    badge: 'ROUTE MISS',
    codeLabel: 'Error Code',
    codeValue: '404',
    title: '页面暂时走丢了',
    description: '你访问的地址可能已经迁移、输入有误，或该内容暂未发布。可以从下方入口继续浏览。',
    hintsTitle: '建议操作',
    hints: [
      '检查地址是否完整',
      '返回首页，从导航继续访问',
      '直接进入博客或留言板',
    ],
    actions: [
      { href: '/', label: '返回首页', ariaLabel: '返回站点首页' },
      { href: '/blog', label: '进入博客', ariaLabel: '前往博客页面' },
      { href: '/guestbook', label: '前往留言板', ariaLabel: '前往留言板页面' },
    ] as SiteActionItem[],
    backActionLabel: '返回上一页',
    backActionAria: '返回上一页',
    quickLinksTitle: '快速入口',
    quickLinks: [
      { href: '/about', label: '关于我' },
      { href: '/moments', label: '说说' },
      { href: '/friends', label: '友情链接' },
    ] as SiteNavItem[],
    panelFootnote: 'NANAMIKU BLOG',
  },
  components: {
    blogFeed: {
      retry: '重试',
      empty: '暂无已发布的文章',
      searchLabel: '智能搜索',
      searchPlaceholder: '输入标题、摘要、标签或分类...',
      searchHint: '支持联想、短语匹配、拼写容错与多关键词组合',
      searchLoadingHint: '正在构建全量搜索索引...',
      searchSuggestionTitle: '联想结果',
      searchSuggestionEnterHint: '回车可直接显示全部匹配结果',
      searchClear: '清空',
      searchResultPrefix: '搜索到',
      searchResultSuffix: '篇相关文章',
      searchEmpty: '没有找到匹配内容，换个关键词试试。',
      featuredBadge: '置顶阅读',
      readSuffix: ' 次阅读',
      likeSuffix: ' 点赞',
      publishedPrefix: '发布：',
      shortLikeSuffix: ' 赞',
      loadError: '加载文章失败，请检查后端服务是否运行',
    },
    latestMoments: {
      title: 'MOMENTS',
      viewAll: '查看全部 →',
      loadFailed: '加载失败',
      retry: '重试',
      empty: '暂无说说',
      imageAltPrefix: '图片 ',
    },
    momentsBoard: {
      countSuffix: ' 条说说',
      loadErrorFallback: '说说加载失败，请稍后再试。',
      submitError: '发布失败，请检查网络后重试。',
      emptyTitle: '还没有说说',
      emptyDescription: '发布第一条说说，记录此刻的想法。',
    },
    momentCard: {
      imageAltPrefix: '图片 ',
      nicknamePlaceholder: '你的昵称',
      commentPlaceholder: '写下评论...',
      send: '发送',
      previewAlt: '预览大图',
      shareTitleSuffix: ' 的说说',
      copiedToast: '链接已复制到剪贴板',
      commentSentToast: '评论已发送',
      commentFailedToast: '评论发送失败，请稍后重试',
    },
    gifEmotePicker: {
      openButton: '插入 GIF 表情',
      closeButton: '收起 GIF 表情',
      hint: '选择后会自动追加到输入框',
      expandAria: '展开 GIF 表情面板',
      collapseAria: '收起 GIF 表情面板',
      insertAriaPrefix: '插入表情：',
      altPrefix: '表情 ',
      tabs: [
        { key: 'miku', label: '初音未来' },
        { key: 'nanamichiaki', label: '七海千秋' },
      ],
    },
    guestbookBoard: {
      postTitle: '发布留言',
      nicknameLabel: '昵称',
      nicknamePlaceholder: '请输入昵称',
      nicknameAuthorPlaceholder: '当前使用作者昵称',
      nicknameAria: '昵称',
      websiteLabel: '网址（可选）',
      websitePlaceholder: 'https://example.com',
      websiteAria: '个人网址',
      messageLabel: '留言内容',
      messagePlaceholder: '想说点什么？欢迎留下你的想法。',
      messageAria: '留言内容',
      submitAria: '发送留言',
      submitLoading: '发送中...',
      submitIdle: '发布',
      sortTabs: [
        { label: '最热', value: 'hot' },
        { label: '最新', value: 'newest' },
        { label: '最早', value: 'oldest' },
      ],
      countSuffix: ' 条留言',
      loadErrorFallback: '留言读取失败，请稍后再试。',
      submitError: '留言提交失败，请检查网络后重试。',
      emptyTitle: '还没有留言',
      emptyDescription: '成为第一个在这里留下足迹的人。',
      validation: {
        nicknameRequired: '昵称不能为空',
        messageRequired: '留言内容不能为空',
        websiteInvalid: '网址格式不合法，请输入 http(s) 链接',
      },
      toasts: {
        submitSuccess: '留言已提交，等待审核',
        authorSubmitSuccess: '作者留言已发布',
        submitFailed: '留言发送失败，请稍后重试',
        replySuccess: '回复已提交，等待审核',
        authorReplySuccess: '作者回复已发布',
        replyFailed: '回复发送失败，请稍后重试',
      },
    },
    guestbookMessageCard: {
      upvoteAria: '赞同',
      downvoteAria: '反对',
      authorBadge: '作者',
      replyButton: '回复',
      replyCountSuffix: ' 条回复',
      nicknamePlaceholder: '你的昵称',
      nicknameAuthorPlaceholder: '当前使用作者昵称',
      contentPlaceholder: '写下你的回复...',
      cancel: '取消',
      submitReply: '回复',
    },
    postComments: {
      sectionTitle: '评论区',
      sectionHint: '评论提交后需审核通过方可展示',
      countSuffix: ' 条',
      formTitle: '发布评论',
      replyPrefix: '正在回复 ',
      cancelReply: '取消回复',
      nicknameLabel: '昵称',
      nicknamePlaceholder: '请输入昵称',
      nicknameAria: '评论昵称',
      nicknameRequired: '*',
      emailLabel: '邮箱（可选）',
      emailPlaceholder: 'name@example.com',
      emailAria: '评论邮箱',
      contentLabel: '评论内容',
      contentPlaceholder: '写下你的看法...',
      contentAria: '评论内容',
      contentRequired: '*',
      contentMaxLength: 800,
      submitIdle: '发送评论',
      submitLoading: '发送中...',
      emptyTitle: '还没有评论',
      emptyDescription: '来发表第一条评论吧，分享你的想法与见解。',
      replyButton: '回复',
      replySuffix: ' 条回复',
      anonymousName: '匿名用户',
      validationEmpty: '昵称和评论内容不能为空。',
      validationEmail: '邮箱格式不正确，请检查后重试。',
      submitSuccess: '评论已提交，审核通过后会显示在列表中。',
      submitFailed: '评论提交失败，请稍后重试。',
      loadFailed: '评论加载失败，请稍后重试。',
    },
    blogPostView: {
      backToList: '返回文章列表',
      readingPrefix: '预计 ',
      readingMinuteSuffix: ' 分钟',
      viewSuffix: ' 次阅读',
      likeSuffix: ' 点赞',
      sidebarReadingTitle: '阅读信息',
      sidebarReadingTime: '预计阅读',
      sidebarWordCount: '全文字数',
      sidebarTocNodes: '目录节点',
      sidebarTagsTitle: '标签',
      noTags: '暂无标签',
      relatedTitle: '相关文章',
      errorMissingSlug: '缺少文章标识',
      errorLoadFailed: '文章加载失败，请检查链接是否正确',
    },
    postLikeBar: {
      sectionTitle: '互动',
      description: '喜欢这篇文章的话，先点个赞，再到评论区聊聊你的看法。',
      likedLabel: '已点赞',
      likeLabel: '点赞',
      goToComments: '去评论区',
      goToCommentsAria: '跳转到评论区',
      likeFailed: '点赞失败，请稍后重试。',
    },
    siteTrend: {
      title: '站点趋势',
      subtitle: '最近 7 天访问热度',
      loading: '加载中...',
      noData: '暂无数据',
      chartAria: '站点趋势图',
    },
    authorStats: {
      posts: '文章',
      categories: '系列',
      views: '访问',
    },
    musicPlayer: {
      prevAria: '上一首',
      nextAria: '下一首',
      pauseAria: '暂停',
      playAria: '播放',
      volumeAria: '音量',
      closeAria: '关闭',
      loopAria: '循环',
      muteAria: '静音',
      unmuteAria: '取消静音',
      noLyrics: '暂无歌词',
    },
    heroShuffleBtn: {
      label: '换图',
      titlePrefix: '切换封面',
    },
    errorState: {
      defaultTitle: '加载失败',
      defaultRetryLabel: '重试',
    },
    readingToc: {
      title: '阅读目录',
    },
    macTerminalCodeBlock: {
      copiedLabel: '已复制',
      copyLabel: '复制代码',
    },
    friendLinkCard: {
      visitAriaPrefix: '访问友链 ',
    },
    heroParallax: {
      coverAltPrefix: '封面 ',
    },
    richContentWithGif: {
      altPrefix: '表情 ',
    },
    blogTopNav: {
      openMenuAria: '打开导航菜单',
      closeMenuAria: '关闭导航菜单',
    },
    aboutGithubProfile: {
      loadError: 'GitHub 数据暂时无法加载，请稍后刷新页面重试。',
      loadingTitle: '正在连接 GitHub 数据',
      loadingHint: '稍等片刻，马上为你展示仓库、活跃度与关联链接。',
      loadingLinks: 'GitHub 相关链接正在加载',
      viewProfile: '查看 GitHub 主页 →',
      stats: {
        repos: 'Repos',
        stars: 'Stars',
        followers: 'Followers',
      },
      activityTitle: 'GitHub 活动概览',
      activitySubtitle: '近 12 个月提交趋势',
      monthSuffix: '月',
      techStackTitle: '技术栈',
      techStackSubtitle: '基于 GitHub 仓库语言自动分析',
      recentReposTitle: '最近活跃项目',
      recentReposSubtitle: '来自 GitHub 最近有更新的仓库',
    },
  },
}
