// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_auth.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredTokens = `-- name: CleanExpiredTokens :exec
DELETE FROM admin_refresh_tokens WHERE expires_at < now()
`

func (q *Queries) CleanExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredTokens)
	return err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (username, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateAdminUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateAdminUserRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateAdminUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO admin_refresh_tokens (admin_user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, created_at
`

type CreateRefreshTokenParams struct {
	AdminUserID uuid.UUID `json:"admin_user_id"`
	TokenHash   string    `json:"token_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.AdminUserID, arg.TokenHash, arg.ExpiresAt)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, email, role, status, display_name, avatar_url, last_login_at, created_at, updated_at
FROM admin_users
WHERE id = $1
`

type GetAdminByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   string             `json:"avatar_url"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (GetAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i GetAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, email, password_hash, role, status, display_name, avatar_url, last_login_at, created_at, updated_at
FROM admin_users
WHERE username = $1 AND status = 'active'
`

type GetAdminByUsernameRow struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    string             `json:"avatar_url"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (GetAdminByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i GetAdminByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrimaryAdminPublicProfile = `-- name: GetPrimaryAdminPublicProfile :one
SELECT username, display_name, avatar_url
FROM admin_users
WHERE status = 'active'
ORDER BY created_at ASC
LIMIT 1
`

type GetPrimaryAdminPublicProfileRow struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) GetPrimaryAdminPublicProfile(ctx context.Context) (GetPrimaryAdminPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPrimaryAdminPublicProfile)
	var i GetPrimaryAdminPublicProfileRow
	err := row.Scan(&i.Username, &i.DisplayName, &i.AvatarUrl)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, admin_user_id, token_hash, expires_at, revoked_at, created_at, last_used_at
FROM admin_refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE admin_refresh_tokens SET revoked_at = now()
WHERE admin_user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, adminUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, adminUserID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE admin_refresh_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const touchRefreshToken = `-- name: TouchRefreshToken :exec
UPDATE admin_refresh_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRefreshToken, id)
	return err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admin_users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, id)
	return err
}

const updateAdminPasswordByUsername = `-- name: UpdateAdminPasswordByUsername :one
UPDATE admin_users
SET password_hash = $2, updated_at = now()
WHERE username = $1
RETURNING id
`

type UpdateAdminPasswordByUsernameParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateAdminPasswordByUsername(ctx context.Context, arg UpdateAdminPasswordByUsernameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateAdminPasswordByUsername, arg.Username, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateAdminProfile = `-- name: UpdateAdminProfile :exec
UPDATE admin_users
SET display_name = $2,
    avatar_url = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateAdminProfileParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	AvatarUrl   string    `json:"avatar_url"`
}

func (q *Queries) UpdateAdminProfile(ctx context.Context, arg UpdateAdminProfileParams) error {
	_, err := q.db.Exec(ctx, updateAdminProfile, arg.ID, arg.DisplayName, arg.AvatarUrl)
	return err
}
