// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package query

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDraftPosts = `-- name: CountDraftPosts :one
SELECT count(*) FROM posts WHERE status = 'draft'
`

func (q *Queries) CountDraftPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDraftPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDailyCommentTrend = `-- name: GetDailyCommentTrend :many
SELECT created_at::date AS day, count(*) AS total
FROM post_comments
WHERE created_at >= $1
GROUP BY created_at::date
ORDER BY day ASC
`

type GetDailyCommentTrendRow struct {
	Day   pgtype.Date `json:"day"`
	Total int64       `json:"total"`
}

func (q *Queries) GetDailyCommentTrend(ctx context.Context, createdAt time.Time) ([]GetDailyCommentTrendRow, error) {
	rows, err := q.db.Query(ctx, getDailyCommentTrend, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyCommentTrendRow{}
	for rows.Next() {
		var i GetDailyCommentTrendRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyLikeTrend = `-- name: GetDailyLikeTrend :many
SELECT created_at::date AS day, count(*) AS total
FROM post_likes
WHERE created_at >= $1
GROUP BY created_at::date
ORDER BY day ASC
`

type GetDailyLikeTrendRow struct {
	Day   pgtype.Date `json:"day"`
	Total int64       `json:"total"`
}

func (q *Queries) GetDailyLikeTrend(ctx context.Context, createdAt time.Time) ([]GetDailyLikeTrendRow, error) {
	rows, err := q.db.Query(ctx, getDailyLikeTrend, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyLikeTrendRow{}
	for rows.Next() {
		var i GetDailyLikeTrendRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyViewTrend = `-- name: GetDailyViewTrend :many
SELECT day, coalesce(sum(pv), 0)::bigint AS pv, coalesce(sum(uv), 0)::bigint AS uv
FROM post_view_daily
WHERE day >= $1
GROUP BY day
ORDER BY day ASC
`

type GetDailyViewTrendRow struct {
	Day pgtype.Date `json:"day"`
	Pv  int64       `json:"pv"`
	Uv  int64       `json:"uv"`
}

func (q *Queries) GetDailyViewTrend(ctx context.Context, day pgtype.Date) ([]GetDailyViewTrendRow, error) {
	rows, err := q.db.Query(ctx, getDailyViewTrend, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyViewTrendRow{}
	for rows.Next() {
		var i GetDailyViewTrendRow
		if err := rows.Scan(&i.Day, &i.Pv, &i.Uv); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalLikeCount = `-- name: GetTotalLikeCount :one
SELECT coalesce(sum(like_count), 0)::bigint FROM posts WHERE status = 'published'
`

func (q *Queries) GetTotalLikeCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalLikeCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalPostCount = `-- name: GetTotalPostCount :one
SELECT count(*) FROM posts WHERE status != 'draft'
`

func (q *Queries) GetTotalPostCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPostCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
