// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveFriendLink = `-- name: ApproveFriendLink :exec
UPDATE friend_links
SET status = 'approved', approved_at = now(), reviewed_by = $2
WHERE id = $1
`

type ApproveFriendLinkParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) ApproveFriendLink(ctx context.Context, arg ApproveFriendLinkParams) error {
	_, err := q.db.Exec(ctx, approveFriendLink, arg.ID, arg.ReviewedBy)
	return err
}

const approveFriendLinkApplication = `-- name: ApproveFriendLinkApplication :exec
UPDATE friend_link_applications
SET status = 'approved',
    reviewed_at = now(),
    review_note = $2,
    reviewed_by = $3
WHERE id = $1
`

type ApproveFriendLinkApplicationParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewNote string      `json:"review_note"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) ApproveFriendLinkApplication(ctx context.Context, arg ApproveFriendLinkApplicationParams) error {
	_, err := q.db.Exec(ctx, approveFriendLinkApplication, arg.ID, arg.ReviewNote, arg.ReviewedBy)
	return err
}

const countAdminFriendLinkApplications = `-- name: CountAdminFriendLinkApplications :one
SELECT count(*)
FROM friend_link_applications
WHERE ($1::friend_link_status IS NULL OR status = $1::friend_link_status)
`

func (q *Queries) CountAdminFriendLinkApplications(ctx context.Context, status NullFriendLinkStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminFriendLinkApplications, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminFriendLinks = `-- name: CountAdminFriendLinks :one
SELECT count(*) FROM friend_links
`

func (q *Queries) CountAdminFriendLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminFriendLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovedFriendLinks = `-- name: CountApprovedFriendLinks :one
SELECT count(*) FROM friend_links WHERE status = 'approved'
`

func (q *Queries) CountApprovedFriendLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedFriendLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFriendLink = `-- name: CreateFriendLink :one
INSERT INTO friend_links (name, description, url, domain, avatar_url, status, sort_order, approved_at, reviewed_by)
VALUES ($1, $2, $3, $4, $5, 'approved', $6, now(), $7)
RETURNING id, created_at
`

type CreateFriendLinkParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Url         string      `json:"url"`
	Domain      string      `json:"domain"`
	AvatarUrl   string      `json:"avatar_url"`
	SortOrder   int32       `json:"sort_order"`
	ReviewedBy  pgtype.UUID `json:"reviewed_by"`
}

type CreateFriendLinkRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFriendLink(ctx context.Context, arg CreateFriendLinkParams) (CreateFriendLinkRow, error) {
	row := q.db.QueryRow(ctx, createFriendLink,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Domain,
		arg.AvatarUrl,
		arg.SortOrder,
		arg.ReviewedBy,
	)
	var i CreateFriendLinkRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createFriendLinkApplication = `-- name: CreateFriendLinkApplication :one
INSERT INTO friend_link_applications (
    site_name,
    site_url,
    avatar_url,
    description,
    contact_email,
    contact_note
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, status
`

type CreateFriendLinkApplicationParams struct {
	SiteName     string `json:"site_name"`
	SiteUrl      string `json:"site_url"`
	AvatarUrl    string `json:"avatar_url"`
	Description  string `json:"description"`
	ContactEmail string `json:"contact_email"`
	ContactNote  string `json:"contact_note"`
}

type CreateFriendLinkApplicationRow struct {
	ID        uuid.UUID        `json:"id"`
	CreatedAt time.Time        `json:"created_at"`
	Status    FriendLinkStatus `json:"status"`
}

func (q *Queries) CreateFriendLinkApplication(ctx context.Context, arg CreateFriendLinkApplicationParams) (CreateFriendLinkApplicationRow, error) {
	row := q.db.QueryRow(ctx, createFriendLinkApplication,
		arg.SiteName,
		arg.SiteUrl,
		arg.AvatarUrl,
		arg.Description,
		arg.ContactEmail,
		arg.ContactNote,
	)
	var i CreateFriendLinkApplicationRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Status)
	return i, err
}

const createFriendLinkHealthLog = `-- name: CreateFriendLinkHealthLog :exec
INSERT INTO friend_link_health_logs (friend_link_id, http_status, latency_ms, result)
VALUES ($1, $2, $3, $4)
`

type CreateFriendLinkHealthLogParams struct {
	FriendLinkID uuid.UUID    `json:"friend_link_id"`
	HttpStatus   int32        `json:"http_status"`
	LatencyMs    int32        `json:"latency_ms"`
	Result       HealthStatus `json:"result"`
}

func (q *Queries) CreateFriendLinkHealthLog(ctx context.Context, arg CreateFriendLinkHealthLogParams) error {
	_, err := q.db.Exec(ctx, createFriendLinkHealthLog,
		arg.FriendLinkID,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.Result,
	)
	return err
}

const deleteFriendLink = `-- name: DeleteFriendLink :exec
DELETE FROM friend_links WHERE id = $1
`

func (q *Queries) DeleteFriendLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendLink, id)
	return err
}

const friendLinkExistsByURL = `-- name: FriendLinkExistsByURL :one
SELECT EXISTS(
    SELECT 1
    FROM friend_links
    WHERE url = $1
)
`

func (q *Queries) FriendLinkExistsByURL(ctx context.Context, url string) (bool, error) {
	row := q.db.QueryRow(ctx, friendLinkExistsByURL, url)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFriendLinkApplicationByID = `-- name: GetFriendLinkApplicationByID :one
SELECT id, site_name, site_url, avatar_url, description, contact_email, contact_note,
       status, created_at, reviewed_at, review_note, reviewed_by
FROM friend_link_applications
WHERE id = $1
`

func (q *Queries) GetFriendLinkApplicationByID(ctx context.Context, id uuid.UUID) (FriendLinkApplication, error) {
	row := q.db.QueryRow(ctx, getFriendLinkApplicationByID, id)
	var i FriendLinkApplication
	err := row.Scan(
		&i.ID,
		&i.SiteName,
		&i.SiteUrl,
		&i.AvatarUrl,
		&i.Description,
		&i.ContactEmail,
		&i.ContactNote,
		&i.Status,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.ReviewedBy,
	)
	return i, err
}

const getFriendLinkByID = `-- name: GetFriendLinkByID :one
SELECT id, name, description, url, domain, avatar_url,
       status, health_status, sort_order,
       created_at, approved_at, reviewed_by, last_checked_at
FROM friend_links
WHERE id = $1
`

func (q *Queries) GetFriendLinkByID(ctx context.Context, id uuid.UUID) (FriendLink, error) {
	row := q.db.QueryRow(ctx, getFriendLinkByID, id)
	var i FriendLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Domain,
		&i.AvatarUrl,
		&i.Status,
		&i.HealthStatus,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.ReviewedBy,
		&i.LastCheckedAt,
	)
	return i, err
}

const listAdminFriendLinkApplications = `-- name: ListAdminFriendLinkApplications :many
SELECT id, site_name, site_url, avatar_url, description, contact_email, contact_note,
       status, created_at, reviewed_at, review_note
FROM friend_link_applications
WHERE ($3::friend_link_status IS NULL OR status = $3::friend_link_status)
ORDER BY CASE status
           WHEN 'pending' THEN 0
           WHEN 'approved' THEN 1
           ELSE 2
         END,
         created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminFriendLinkApplicationsParams struct {
	Limit  int32                `json:"limit"`
	Offset int32                `json:"offset"`
	Status NullFriendLinkStatus `json:"status"`
}

type ListAdminFriendLinkApplicationsRow struct {
	ID           uuid.UUID          `json:"id"`
	SiteName     string             `json:"site_name"`
	SiteUrl      string             `json:"site_url"`
	AvatarUrl    string             `json:"avatar_url"`
	Description  string             `json:"description"`
	ContactEmail string             `json:"contact_email"`
	ContactNote  string             `json:"contact_note"`
	Status       FriendLinkStatus   `json:"status"`
	CreatedAt    time.Time          `json:"created_at"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNote   string             `json:"review_note"`
}

func (q *Queries) ListAdminFriendLinkApplications(ctx context.Context, arg ListAdminFriendLinkApplicationsParams) ([]ListAdminFriendLinkApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listAdminFriendLinkApplications, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminFriendLinkApplicationsRow{}
	for rows.Next() {
		var i ListAdminFriendLinkApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteName,
			&i.SiteUrl,
			&i.AvatarUrl,
			&i.Description,
			&i.ContactEmail,
			&i.ContactNote,
			&i.Status,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.ReviewNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminFriendLinks = `-- name: ListAdminFriendLinks :many
SELECT id, name, description, url, domain, avatar_url,
       status, health_status, sort_order,
       created_at, approved_at, last_checked_at
FROM friend_links
ORDER BY sort_order ASC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminFriendLinksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminFriendLinksRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Url           string             `json:"url"`
	Domain        string             `json:"domain"`
	AvatarUrl     string             `json:"avatar_url"`
	Status        FriendLinkStatus   `json:"status"`
	HealthStatus  HealthStatus       `json:"health_status"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     time.Time          `json:"created_at"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
}

func (q *Queries) ListAdminFriendLinks(ctx context.Context, arg ListAdminFriendLinksParams) ([]ListAdminFriendLinksRow, error) {
	rows, err := q.db.Query(ctx, listAdminFriendLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminFriendLinksRow{}
	for rows.Next() {
		var i ListAdminFriendLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.Domain,
			&i.AvatarUrl,
			&i.Status,
			&i.HealthStatus,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedFriendLinks = `-- name: ListApprovedFriendLinks :many
SELECT id, name, description, url, avatar_url, health_status
FROM friend_links
WHERE status = 'approved'
ORDER BY sort_order ASC, approved_at DESC
`

type ListApprovedFriendLinksRow struct {
	ID           uuid.UUID    `json:"id"`
	Name         string       `json:"name"`
	Description  string       `json:"description"`
	Url          string       `json:"url"`
	AvatarUrl    string       `json:"avatar_url"`
	HealthStatus HealthStatus `json:"health_status"`
}

func (q *Queries) ListApprovedFriendLinks(ctx context.Context) ([]ListApprovedFriendLinksRow, error) {
	rows, err := q.db.Query(ctx, listApprovedFriendLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedFriendLinksRow{}
	for rows.Next() {
		var i ListApprovedFriendLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.AvatarUrl,
			&i.HealthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendLinksForHealthCheck = `-- name: ListFriendLinksForHealthCheck :many
SELECT id, url FROM friend_links
WHERE status = 'approved'
  AND (last_checked_at IS NULL OR last_checked_at < now() - interval '1 hour')
`

type ListFriendLinksForHealthCheckRow struct {
	ID  uuid.UUID `json:"id"`
	Url string    `json:"url"`
}

func (q *Queries) ListFriendLinksForHealthCheck(ctx context.Context) ([]ListFriendLinksForHealthCheckRow, error) {
	rows, err := q.db.Query(ctx, listFriendLinksForHealthCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendLinksForHealthCheckRow{}
	for rows.Next() {
		var i ListFriendLinksForHealthCheckRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingFriendLinkApplicationExistsByURL = `-- name: PendingFriendLinkApplicationExistsByURL :one
SELECT EXISTS(
    SELECT 1
    FROM friend_link_applications
    WHERE site_url = $1
      AND status = 'pending'
)
`

func (q *Queries) PendingFriendLinkApplicationExistsByURL(ctx context.Context, siteUrl string) (bool, error) {
	row := q.db.QueryRow(ctx, pendingFriendLinkApplicationExistsByURL, siteUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rejectFriendLink = `-- name: RejectFriendLink :exec
UPDATE friend_links
SET status = 'rejected', reviewed_by = $2
WHERE id = $1
`

type RejectFriendLinkParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) RejectFriendLink(ctx context.Context, arg RejectFriendLinkParams) error {
	_, err := q.db.Exec(ctx, rejectFriendLink, arg.ID, arg.ReviewedBy)
	return err
}

const rejectFriendLinkApplication = `-- name: RejectFriendLinkApplication :exec
UPDATE friend_link_applications
SET status = 'rejected',
    reviewed_at = now(),
    review_note = $2,
    reviewed_by = $3
WHERE id = $1
`

type RejectFriendLinkApplicationParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewNote string      `json:"review_note"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) RejectFriendLinkApplication(ctx context.Context, arg RejectFriendLinkApplicationParams) error {
	_, err := q.db.Exec(ctx, rejectFriendLinkApplication, arg.ID, arg.ReviewNote, arg.ReviewedBy)
	return err
}

const updateFriendLink = `-- name: UpdateFriendLink :exec
UPDATE friend_links
SET name = $2, description = $3, url = $4, domain = $5,
    avatar_url = $6, sort_order = $7
WHERE id = $1
`

type UpdateFriendLinkParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Url         string    `json:"url"`
	Domain      string    `json:"domain"`
	AvatarUrl   string    `json:"avatar_url"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) UpdateFriendLink(ctx context.Context, arg UpdateFriendLinkParams) error {
	_, err := q.db.Exec(ctx, updateFriendLink,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Domain,
		arg.AvatarUrl,
		arg.SortOrder,
	)
	return err
}

const updateFriendLinkHealth = `-- name: UpdateFriendLinkHealth :exec
UPDATE friend_links
SET health_status = $2, last_checked_at = now()
WHERE id = $1
`

type UpdateFriendLinkHealthParams struct {
	ID           uuid.UUID    `json:"id"`
	HealthStatus HealthStatus `json:"health_status"`
}

func (q *Queries) UpdateFriendLinkHealth(ctx context.Context, arg UpdateFriendLinkHealthParams) error {
	_, err := q.db.Exec(ctx, updateFriendLinkHealth, arg.ID, arg.HealthStatus)
	return err
}
