// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FriendLinkStatus string

const (
	FriendLinkStatusPending  FriendLinkStatus = "pending"
	FriendLinkStatusApproved FriendLinkStatus = "approved"
	FriendLinkStatusRejected FriendLinkStatus = "rejected"
)

func (e *FriendLinkStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendLinkStatus(s)
	case string:
		*e = FriendLinkStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendLinkStatus: %T", src)
	}
	return nil
}

type NullFriendLinkStatus struct {
	FriendLinkStatus FriendLinkStatus `json:"friend_link_status"`
	Valid            bool             `json:"valid"` // Valid is true if FriendLinkStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendLinkStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendLinkStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendLinkStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendLinkStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendLinkStatus), nil
}

type HealthStatus string

const (
	HealthStatusOk      HealthStatus = "ok"
	HealthStatusDown    HealthStatus = "down"
	HealthStatusUnknown HealthStatus = "unknown"
)

func (e *HealthStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HealthStatus(s)
	case string:
		*e = HealthStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HealthStatus: %T", src)
	}
	return nil
}

type NullHealthStatus struct {
	HealthStatus HealthStatus `json:"health_status"`
	Valid        bool         `json:"valid"` // Valid is true if HealthStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHealthStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HealthStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HealthStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHealthStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HealthStatus), nil
}

type ModerationStatus string

const (
	ModerationStatusPending  ModerationStatus = "pending"
	ModerationStatusApproved ModerationStatus = "approved"
	ModerationStatusRejected ModerationStatus = "rejected"
	ModerationStatusHidden   ModerationStatus = "hidden"
)

func (e *ModerationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModerationStatus(s)
	case string:
		*e = ModerationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ModerationStatus: %T", src)
	}
	return nil
}

type NullModerationStatus struct {
	ModerationStatus ModerationStatus `json:"moderation_status"`
	Valid            bool             `json:"valid"` // Valid is true if ModerationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModerationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ModerationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModerationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModerationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModerationStatus), nil
}

type MomentPublishStatus string

const (
	MomentPublishStatusDraft     MomentPublishStatus = "draft"
	MomentPublishStatusPublished MomentPublishStatus = "published"
	MomentPublishStatusScheduled MomentPublishStatus = "scheduled"
	MomentPublishStatusArchived  MomentPublishStatus = "archived"
)

func (e *MomentPublishStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MomentPublishStatus(s)
	case string:
		*e = MomentPublishStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MomentPublishStatus: %T", src)
	}
	return nil
}

type NullMomentPublishStatus struct {
	MomentPublishStatus MomentPublishStatus `json:"moment_publish_status"`
	Valid               bool                `json:"valid"` // Valid is true if MomentPublishStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMomentPublishStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MomentPublishStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MomentPublishStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMomentPublishStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MomentPublishStatus), nil
}

type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusScheduled PostStatus = "scheduled"
	PostStatusArchived  PostStatus = "archived"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus `json:"post_status"`
	Valid      bool       `json:"valid"` // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type VoteType string

const (
	VoteTypeUp   VoteType = "up"
	VoteTypeDown VoteType = "down"
)

func (e *VoteType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VoteType(s)
	case string:
		*e = VoteType(s)
	default:
		return fmt.Errorf("unsupported scan type for VoteType: %T", src)
	}
	return nil
}

type NullVoteType struct {
	VoteType VoteType `json:"vote_type"`
	Valid    bool     `json:"valid"` // Valid is true if VoteType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVoteType) Scan(value interface{}) error {
	if value == nil {
		ns.VoteType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VoteType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVoteType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VoteType), nil
}

type AdminRefreshToken struct {
	ID          uuid.UUID          `json:"id"`
	AdminUserID uuid.UUID          `json:"admin_user_id"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   time.Time          `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   time.Time          `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

type AdminUser struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    string             `json:"avatar_url"`
}

type AnalyticsPageview struct {
	ID           uuid.UUID   `json:"id"`
	SessionID    uuid.UUID   `json:"session_id"`
	VisitorID    pgtype.UUID `json:"visitor_id"`
	Path         string      `json:"path"`
	Title        string      `json:"title"`
	Referrer     string      `json:"referrer"`
	ReferrerHost string      `json:"referrer_host"`
	Channel      string      `json:"channel"`
	Browser      string      `json:"browser"`
	Os           string      `json:"os"`
	Device       string      `json:"device"`
	CountryCode  string      `json:"country_code"`
	Region       string      `json:"region"`
	City         string      `json:"city"`
	Timezone     string      `json:"timezone"`
	Language     string      `json:"language"`
	OccurredAt   time.Time   `json:"occurred_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type AnalyticsSession struct {
	ID           uuid.UUID   `json:"id"`
	SessionKey   string      `json:"session_key"`
	VisitorID    pgtype.UUID `json:"visitor_id"`
	StartedAt    time.Time   `json:"started_at"`
	LastSeenAt   time.Time   `json:"last_seen_at"`
	EntryPath    string      `json:"entry_path"`
	ExitPath     string      `json:"exit_path"`
	Referrer     string      `json:"referrer"`
	ReferrerHost string      `json:"referrer_host"`
	Channel      string      `json:"channel"`
	Browser      string      `json:"browser"`
	Os           string      `json:"os"`
	Device       string      `json:"device"`
	CountryCode  string      `json:"country_code"`
	Region       string      `json:"region"`
	City         string      `json:"city"`
	Timezone     string      `json:"timezone"`
	Language     string      `json:"language"`
	Pageviews    int32       `json:"pageviews"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type AuditLog struct {
	ID         uuid.UUID       `json:"id"`
	AdminID    pgtype.UUID     `json:"admin_id"`
	Action     string          `json:"action"`
	TargetType string          `json:"target_type"`
	TargetID   string          `json:"target_id"`
	Detail     json.RawMessage `json:"detail"`
	Ip         string          `json:"ip"`
	CreatedAt  time.Time       `json:"created_at"`
}

type BlockedIp struct {
	ID        uuid.UUID          `json:"id"`
	IpHash    string             `json:"ip_hash"`
	Reason    string             `json:"reason"`
	BlockedAt time.Time          `json:"blocked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type FriendLink struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Url           string             `json:"url"`
	Domain        string             `json:"domain"`
	AvatarUrl     string             `json:"avatar_url"`
	Status        FriendLinkStatus   `json:"status"`
	HealthStatus  HealthStatus       `json:"health_status"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     time.Time          `json:"created_at"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
	ReviewedBy    pgtype.UUID        `json:"reviewed_by"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
}

type FriendLinkHealthLog struct {
	ID           uuid.UUID    `json:"id"`
	FriendLinkID uuid.UUID    `json:"friend_link_id"`
	HttpStatus   int32        `json:"http_status"`
	LatencyMs    int32        `json:"latency_ms"`
	Result       HealthStatus `json:"result"`
	CheckedAt    time.Time    `json:"checked_at"`
}

type GuestbookMessage struct {
	ID            uuid.UUID        `json:"id"`
	ParentID      pgtype.UUID      `json:"parent_id"`
	AuthorName    string           `json:"author_name"`
	AuthorWebsite string           `json:"author_website"`
	Content       string           `json:"content"`
	Status        ModerationStatus `json:"status"`
	VoteScore     int32            `json:"vote_score"`
	IpHash        string           `json:"ip_hash"`
	UaHash        string           `json:"ua_hash"`
	CreatedAt     time.Time        `json:"created_at"`
	ReviewedBy    pgtype.UUID      `json:"reviewed_by"`
}

type GuestbookVote struct {
	MessageID uuid.UUID `json:"message_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
	Vote      VoteType  `json:"vote"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Moment struct {
	ID              uuid.UUID           `json:"id"`
	AuthorName      string              `json:"author_name"`
	Content         string              `json:"content"`
	ImageUrls       json.RawMessage     `json:"image_urls"`
	Status          ModerationStatus    `json:"status"`
	LikeCount       int64               `json:"like_count"`
	RepostCount     int64               `json:"repost_count"`
	CommentCount    int64               `json:"comment_count"`
	IpHash          string              `json:"ip_hash"`
	UaHash          string              `json:"ua_hash"`
	CreatedAt       time.Time           `json:"created_at"`
	ReviewedBy      pgtype.UUID         `json:"reviewed_by"`
	PublishStatus   MomentPublishStatus `json:"publish_status"`
	PublishedAt     pgtype.Timestamptz  `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz  `json:"scheduled_at"`
	AuthorAvatarUrl string              `json:"author_avatar_url"`
}

type MomentComment struct {
	ID         uuid.UUID        `json:"id"`
	MomentID   uuid.UUID        `json:"moment_id"`
	AuthorName string           `json:"author_name"`
	Content    string           `json:"content"`
	Status     ModerationStatus `json:"status"`
	LikeCount  int64            `json:"like_count"`
	IpHash     string           `json:"ip_hash"`
	UaHash     string           `json:"ua_hash"`
	CreatedAt  time.Time        `json:"created_at"`
	ReviewedBy pgtype.UUID      `json:"reviewed_by"`
}

type MomentCommentLike struct {
	CommentID uuid.UUID `json:"comment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
	CreatedAt time.Time `json:"created_at"`
}

type MomentLike struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
	CreatedAt time.Time `json:"created_at"`
}

type MomentRepost struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Excerpt         string             `json:"excerpt"`
	ContentMarkdown string             `json:"content_markdown"`
	HeroImageUrl    string             `json:"hero_image_url"`
	Category        string             `json:"category"`
	Status          PostStatus         `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	ViewCount       int64              `json:"view_count"`
	LikeCount       int64              `json:"like_count"`
	CommentCount    int64              `json:"comment_count"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	SearchVector    interface{}        `json:"search_vector"`
}

type PostComment struct {
	ID            uuid.UUID          `json:"id"`
	PostID        uuid.UUID          `json:"post_id"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	AuthorName    string             `json:"author_name"`
	AuthorEmail   string             `json:"author_email"`
	AuthorWebsite string             `json:"author_website"`
	Content       string             `json:"content"`
	Status        ModerationStatus   `json:"status"`
	IpHash        string             `json:"ip_hash"`
	UaHash        string             `json:"ua_hash"`
	CreatedAt     time.Time          `json:"created_at"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
	ReviewedBy    pgtype.UUID        `json:"reviewed_by"`
}

type PostLike struct {
	PostID    uuid.UUID `json:"post_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PostRevision struct {
	ID              uuid.UUID   `json:"id"`
	PostID          uuid.UUID   `json:"post_id"`
	Title           string      `json:"title"`
	Excerpt         string      `json:"excerpt"`
	ContentMarkdown string      `json:"content_markdown"`
	HeroImageUrl    string      `json:"hero_image_url"`
	Category        string      `json:"category"`
	EditorID        pgtype.UUID `json:"editor_id"`
	CreatedAt       time.Time   `json:"created_at"`
}

type PostTag struct {
	PostID uuid.UUID `json:"post_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

type PostViewDaily struct {
	PostID uuid.UUID   `json:"post_id"`
	Day    pgtype.Date `json:"day"`
	Pv     int64       `json:"pv"`
	Uv     int64       `json:"uv"`
}

type SensitiveWord struct {
	ID        uuid.UUID `json:"id"`
	Word      string    `json:"word"`
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"created_at"`
}

type Tag struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

type Visitor struct {
	ID          uuid.UUID `json:"id"`
	FirstSeenAt time.Time `json:"first_seen_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
	IpHash      string    `json:"ip_hash"`
	UaHash      string    `json:"ua_hash"`
}
