// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moments.sql

package query

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkMomentCommentLike = `-- name: CheckMomentCommentLike :one
SELECT count(*) FROM moment_comment_likes WHERE comment_id = $1 AND visitor_id = $2
`

type CheckMomentCommentLikeParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CheckMomentCommentLike(ctx context.Context, arg CheckMomentCommentLikeParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkMomentCommentLike, arg.CommentID, arg.VisitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkMomentLike = `-- name: CheckMomentLike :one
SELECT count(*) FROM moment_likes WHERE moment_id = $1 AND visitor_id = $2
`

type CheckMomentLikeParams struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CheckMomentLike(ctx context.Context, arg CheckMomentLikeParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkMomentLike, arg.MomentID, arg.VisitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkMomentRepost = `-- name: CheckMomentRepost :one
SELECT count(*) FROM moment_reposts WHERE moment_id = $1 AND visitor_id = $2
`

type CheckMomentRepostParams struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CheckMomentRepost(ctx context.Context, arg CheckMomentRepostParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkMomentRepost, arg.MomentID, arg.VisitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminMoments = `-- name: CountAdminMoments :one
SELECT count(*) FROM moments
`

func (q *Queries) CountAdminMoments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminMoments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMomentComments = `-- name: CountMomentComments :one
SELECT count(*) FROM moment_comments WHERE moment_id = $1 AND status = 'approved'
`

func (q *Queries) CountMomentComments(ctx context.Context, momentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMomentComments, momentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMoments = `-- name: CountMoments :one
SELECT count(*)
FROM moments
WHERE status = 'approved'
  AND publish_status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= now()
`

func (q *Queries) CountMoments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMoments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMoment = `-- name: CreateMoment :one
INSERT INTO moments (author_name, author_avatar_url, content, image_urls, ip_hash, ua_hash, publish_status, published_at, scheduled_at)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    CASE WHEN $7 = 'published'::moment_publish_status THEN now() ELSE NULL::timestamptz END,
    CASE WHEN $7 = 'scheduled'::moment_publish_status THEN $8::timestamptz ELSE NULL::timestamptz END
)
RETURNING id, created_at
`

type CreateMomentParams struct {
	AuthorName      string              `json:"author_name"`
	AuthorAvatarUrl string              `json:"author_avatar_url"`
	Content         string              `json:"content"`
	ImageUrls       json.RawMessage     `json:"image_urls"`
	IpHash          string              `json:"ip_hash"`
	UaHash          string              `json:"ua_hash"`
	PublishStatus   MomentPublishStatus `json:"publish_status"`
	Column8         time.Time           `json:"column_8"`
}

type CreateMomentRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateMoment(ctx context.Context, arg CreateMomentParams) (CreateMomentRow, error) {
	row := q.db.QueryRow(ctx, createMoment,
		arg.AuthorName,
		arg.AuthorAvatarUrl,
		arg.Content,
		arg.ImageUrls,
		arg.IpHash,
		arg.UaHash,
		arg.PublishStatus,
		arg.Column8,
	)
	var i CreateMomentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createMomentComment = `-- name: CreateMomentComment :one
INSERT INTO moment_comments (moment_id, author_name, content, ip_hash, ua_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateMomentCommentParams struct {
	MomentID   uuid.UUID `json:"moment_id"`
	AuthorName string    `json:"author_name"`
	Content    string    `json:"content"`
	IpHash     string    `json:"ip_hash"`
	UaHash     string    `json:"ua_hash"`
}

type CreateMomentCommentRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateMomentComment(ctx context.Context, arg CreateMomentCommentParams) (CreateMomentCommentRow, error) {
	row := q.db.QueryRow(ctx, createMomentComment,
		arg.MomentID,
		arg.AuthorName,
		arg.Content,
		arg.IpHash,
		arg.UaHash,
	)
	var i CreateMomentCommentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createMomentCommentLike = `-- name: CreateMomentCommentLike :exec
INSERT INTO moment_comment_likes (comment_id, visitor_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateMomentCommentLikeParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CreateMomentCommentLike(ctx context.Context, arg CreateMomentCommentLikeParams) error {
	_, err := q.db.Exec(ctx, createMomentCommentLike, arg.CommentID, arg.VisitorID)
	return err
}

const createMomentLike = `-- name: CreateMomentLike :exec
INSERT INTO moment_likes (moment_id, visitor_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateMomentLikeParams struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CreateMomentLike(ctx context.Context, arg CreateMomentLikeParams) error {
	_, err := q.db.Exec(ctx, createMomentLike, arg.MomentID, arg.VisitorID)
	return err
}

const createMomentRepost = `-- name: CreateMomentRepost :exec
INSERT INTO moment_reposts (moment_id, visitor_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateMomentRepostParams struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CreateMomentRepost(ctx context.Context, arg CreateMomentRepostParams) error {
	_, err := q.db.Exec(ctx, createMomentRepost, arg.MomentID, arg.VisitorID)
	return err
}

const decrementMomentCommentLikeCount = `-- name: DecrementMomentCommentLikeCount :exec
UPDATE moment_comments SET like_count = GREATEST(like_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementMomentCommentLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementMomentCommentLikeCount, id)
	return err
}

const decrementMomentLikeCount = `-- name: DecrementMomentLikeCount :exec
UPDATE moments SET like_count = GREATEST(like_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementMomentLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementMomentLikeCount, id)
	return err
}

const decrementMomentRepostCount = `-- name: DecrementMomentRepostCount :exec
UPDATE moments SET repost_count = GREATEST(repost_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementMomentRepostCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementMomentRepostCount, id)
	return err
}

const deleteMoment = `-- name: DeleteMoment :exec
DELETE FROM moments WHERE id = $1
`

func (q *Queries) DeleteMoment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMoment, id)
	return err
}

const deleteMomentCommentLike = `-- name: DeleteMomentCommentLike :exec
DELETE FROM moment_comment_likes WHERE comment_id = $1 AND visitor_id = $2
`

type DeleteMomentCommentLikeParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) DeleteMomentCommentLike(ctx context.Context, arg DeleteMomentCommentLikeParams) error {
	_, err := q.db.Exec(ctx, deleteMomentCommentLike, arg.CommentID, arg.VisitorID)
	return err
}

const deleteMomentLike = `-- name: DeleteMomentLike :exec
DELETE FROM moment_likes WHERE moment_id = $1 AND visitor_id = $2
`

type DeleteMomentLikeParams struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) DeleteMomentLike(ctx context.Context, arg DeleteMomentLikeParams) error {
	_, err := q.db.Exec(ctx, deleteMomentLike, arg.MomentID, arg.VisitorID)
	return err
}

const deleteMomentRepost = `-- name: DeleteMomentRepost :exec
DELETE FROM moment_reposts WHERE moment_id = $1 AND visitor_id = $2
`

type DeleteMomentRepostParams struct {
	MomentID  uuid.UUID `json:"moment_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) DeleteMomentRepost(ctx context.Context, arg DeleteMomentRepostParams) error {
	_, err := q.db.Exec(ctx, deleteMomentRepost, arg.MomentID, arg.VisitorID)
	return err
}

const getMomentByID = `-- name: GetMomentByID :one
SELECT id, author_name, author_avatar_url, content, image_urls, status, like_count,
       repost_count, comment_count, publish_status, published_at, scheduled_at, created_at
FROM moments
WHERE id = $1
`

type GetMomentByIDRow struct {
	ID              uuid.UUID           `json:"id"`
	AuthorName      string              `json:"author_name"`
	AuthorAvatarUrl string              `json:"author_avatar_url"`
	Content         string              `json:"content"`
	ImageUrls       json.RawMessage     `json:"image_urls"`
	Status          ModerationStatus    `json:"status"`
	LikeCount       int64               `json:"like_count"`
	RepostCount     int64               `json:"repost_count"`
	CommentCount    int64               `json:"comment_count"`
	PublishStatus   MomentPublishStatus `json:"publish_status"`
	PublishedAt     pgtype.Timestamptz  `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz  `json:"scheduled_at"`
	CreatedAt       time.Time           `json:"created_at"`
}

func (q *Queries) GetMomentByID(ctx context.Context, id uuid.UUID) (GetMomentByIDRow, error) {
	row := q.db.QueryRow(ctx, getMomentByID, id)
	var i GetMomentByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorName,
		&i.AuthorAvatarUrl,
		&i.Content,
		&i.ImageUrls,
		&i.Status,
		&i.LikeCount,
		&i.RepostCount,
		&i.CommentCount,
		&i.PublishStatus,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVisitorMomentCommentLikes = `-- name: GetVisitorMomentCommentLikes :many
SELECT comment_id FROM moment_comment_likes
WHERE visitor_id = $1 AND comment_id = ANY($2::uuid[])
`

type GetVisitorMomentCommentLikesParams struct {
	VisitorID uuid.UUID   `json:"visitor_id"`
	Column2   []uuid.UUID `json:"column_2"`
}

func (q *Queries) GetVisitorMomentCommentLikes(ctx context.Context, arg GetVisitorMomentCommentLikesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getVisitorMomentCommentLikes, arg.VisitorID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var comment_id uuid.UUID
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorMomentLikes = `-- name: GetVisitorMomentLikes :many
SELECT moment_id FROM moment_likes
WHERE visitor_id = $1 AND moment_id = ANY($2::uuid[])
`

type GetVisitorMomentLikesParams struct {
	VisitorID uuid.UUID   `json:"visitor_id"`
	Column2   []uuid.UUID `json:"column_2"`
}

func (q *Queries) GetVisitorMomentLikes(ctx context.Context, arg GetVisitorMomentLikesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getVisitorMomentLikes, arg.VisitorID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var moment_id uuid.UUID
		if err := rows.Scan(&moment_id); err != nil {
			return nil, err
		}
		items = append(items, moment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorMomentReposts = `-- name: GetVisitorMomentReposts :many
SELECT moment_id FROM moment_reposts
WHERE visitor_id = $1 AND moment_id = ANY($2::uuid[])
`

type GetVisitorMomentRepostsParams struct {
	VisitorID uuid.UUID   `json:"visitor_id"`
	Column2   []uuid.UUID `json:"column_2"`
}

func (q *Queries) GetVisitorMomentReposts(ctx context.Context, arg GetVisitorMomentRepostsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getVisitorMomentReposts, arg.VisitorID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var moment_id uuid.UUID
		if err := rows.Scan(&moment_id); err != nil {
			return nil, err
		}
		items = append(items, moment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hideMoment = `-- name: HideMoment :exec
UPDATE moments SET status = 'hidden', reviewed_by = $2 WHERE id = $1
`

type HideMomentParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) HideMoment(ctx context.Context, arg HideMomentParams) error {
	_, err := q.db.Exec(ctx, hideMoment, arg.ID, arg.ReviewedBy)
	return err
}

const hideMomentComment = `-- name: HideMomentComment :exec
UPDATE moment_comments SET status = 'hidden', reviewed_by = $2 WHERE id = $1
`

type HideMomentCommentParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) HideMomentComment(ctx context.Context, arg HideMomentCommentParams) error {
	_, err := q.db.Exec(ctx, hideMomentComment, arg.ID, arg.ReviewedBy)
	return err
}

const incrementMomentCommentCount = `-- name: IncrementMomentCommentCount :exec
UPDATE moments SET comment_count = comment_count + 1 WHERE id = $1
`

func (q *Queries) IncrementMomentCommentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMomentCommentCount, id)
	return err
}

const incrementMomentCommentLikeCount = `-- name: IncrementMomentCommentLikeCount :exec
UPDATE moment_comments SET like_count = like_count + 1 WHERE id = $1
`

func (q *Queries) IncrementMomentCommentLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMomentCommentLikeCount, id)
	return err
}

const incrementMomentLikeCount = `-- name: IncrementMomentLikeCount :exec
UPDATE moments SET like_count = like_count + 1 WHERE id = $1
`

func (q *Queries) IncrementMomentLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMomentLikeCount, id)
	return err
}

const incrementMomentRepostCount = `-- name: IncrementMomentRepostCount :exec
UPDATE moments SET repost_count = repost_count + 1 WHERE id = $1
`

func (q *Queries) IncrementMomentRepostCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMomentRepostCount, id)
	return err
}

const listAdminMoments = `-- name: ListAdminMoments :many
SELECT id, author_name, author_avatar_url, content, image_urls, status, like_count,
       repost_count, comment_count, publish_status, published_at, scheduled_at, created_at
FROM moments
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminMomentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminMomentsRow struct {
	ID              uuid.UUID           `json:"id"`
	AuthorName      string              `json:"author_name"`
	AuthorAvatarUrl string              `json:"author_avatar_url"`
	Content         string              `json:"content"`
	ImageUrls       json.RawMessage     `json:"image_urls"`
	Status          ModerationStatus    `json:"status"`
	LikeCount       int64               `json:"like_count"`
	RepostCount     int64               `json:"repost_count"`
	CommentCount    int64               `json:"comment_count"`
	PublishStatus   MomentPublishStatus `json:"publish_status"`
	PublishedAt     pgtype.Timestamptz  `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz  `json:"scheduled_at"`
	CreatedAt       time.Time           `json:"created_at"`
}

func (q *Queries) ListAdminMoments(ctx context.Context, arg ListAdminMomentsParams) ([]ListAdminMomentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminMoments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminMomentsRow{}
	for rows.Next() {
		var i ListAdminMomentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Content,
			&i.ImageUrls,
			&i.Status,
			&i.LikeCount,
			&i.RepostCount,
			&i.CommentCount,
			&i.PublishStatus,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestMoments = `-- name: ListLatestMoments :many
SELECT id, author_name, author_avatar_url, content, image_urls, created_at
FROM moments
WHERE status = 'approved'
  AND publish_status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= now()
ORDER BY published_at DESC, created_at DESC
LIMIT $1
`

type ListLatestMomentsRow struct {
	ID              uuid.UUID       `json:"id"`
	AuthorName      string          `json:"author_name"`
	AuthorAvatarUrl string          `json:"author_avatar_url"`
	Content         string          `json:"content"`
	ImageUrls       json.RawMessage `json:"image_urls"`
	CreatedAt       time.Time       `json:"created_at"`
}

func (q *Queries) ListLatestMoments(ctx context.Context, limit int32) ([]ListLatestMomentsRow, error) {
	rows, err := q.db.Query(ctx, listLatestMoments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestMomentsRow{}
	for rows.Next() {
		var i ListLatestMomentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Content,
			&i.ImageUrls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMomentComments = `-- name: ListMomentComments :many
SELECT id, moment_id, author_name, content, like_count, created_at
FROM moment_comments
WHERE moment_id = $1 AND status = 'approved'
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListMomentCommentsParams struct {
	MomentID uuid.UUID `json:"moment_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListMomentCommentsRow struct {
	ID         uuid.UUID `json:"id"`
	MomentID   uuid.UUID `json:"moment_id"`
	AuthorName string    `json:"author_name"`
	Content    string    `json:"content"`
	LikeCount  int64     `json:"like_count"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListMomentComments(ctx context.Context, arg ListMomentCommentsParams) ([]ListMomentCommentsRow, error) {
	rows, err := q.db.Query(ctx, listMomentComments, arg.MomentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMomentCommentsRow{}
	for rows.Next() {
		var i ListMomentCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MomentID,
			&i.AuthorName,
			&i.Content,
			&i.LikeCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMoments = `-- name: ListMoments :many
SELECT
    m.id,
    m.author_name,
    m.author_avatar_url,
    m.content,
    m.image_urls,
    m.like_count,
    m.repost_count,
    m.comment_count,
    m.publish_status,
    m.published_at,
    m.scheduled_at,
    m.created_at,
    COALESCE((
        SELECT jsonb_agg(
            jsonb_build_object(
                'id', mc.id,
                'author_name', mc.author_name,
                'content', mc.content,
                'like_count', mc.like_count,
                'created_at', to_char(mc.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
                'liked', EXISTS (
                    SELECT 1
                    FROM moment_comment_likes mcl
                    WHERE mcl.comment_id = mc.id
                      AND mcl.visitor_id = $1
                )
            )
            ORDER BY mc.created_at ASC
        )
        FROM moment_comments mc
        WHERE mc.moment_id = m.id
          AND mc.status = 'approved'
    ), '[]'::jsonb) AS comments
FROM moments m
WHERE m.status = 'approved'
  AND m.publish_status = 'published'
  AND m.published_at IS NOT NULL
  AND m.published_at <= now()
ORDER BY m.published_at DESC, m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMomentsParams struct {
	VisitorID uuid.UUID `json:"visitor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListMomentsRow struct {
	ID              uuid.UUID           `json:"id"`
	AuthorName      string              `json:"author_name"`
	AuthorAvatarUrl string              `json:"author_avatar_url"`
	Content         string              `json:"content"`
	ImageUrls       json.RawMessage     `json:"image_urls"`
	LikeCount       int64               `json:"like_count"`
	RepostCount     int64               `json:"repost_count"`
	CommentCount    int64               `json:"comment_count"`
	PublishStatus   MomentPublishStatus `json:"publish_status"`
	PublishedAt     pgtype.Timestamptz  `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz  `json:"scheduled_at"`
	CreatedAt       time.Time           `json:"created_at"`
	Comments        json.RawMessage     `json:"comments"`
}

func (q *Queries) ListMoments(ctx context.Context, arg ListMomentsParams) ([]ListMomentsRow, error) {
	rows, err := q.db.Query(ctx, listMoments, arg.VisitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMomentsRow{}
	for rows.Next() {
		var i ListMomentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Content,
			&i.ImageUrls,
			&i.LikeCount,
			&i.RepostCount,
			&i.CommentCount,
			&i.PublishStatus,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledMomentsDue = `-- name: ListScheduledMomentsDue :many
SELECT id
FROM moments
WHERE status = 'approved' AND publish_status = 'scheduled' AND scheduled_at <= now()
`

func (q *Queries) ListScheduledMomentsDue(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listScheduledMomentsDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishMoment = `-- name: PublishMoment :exec
UPDATE moments
SET publish_status = 'published', published_at = now(), scheduled_at = NULL
WHERE id = $1
`

func (q *Queries) PublishMoment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, publishMoment, id)
	return err
}

const scheduleMoment = `-- name: ScheduleMoment :exec
UPDATE moments
SET publish_status = 'scheduled', scheduled_at = $2, published_at = NULL
WHERE id = $1
`

type ScheduleMomentParams struct {
	ID          uuid.UUID          `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) ScheduleMoment(ctx context.Context, arg ScheduleMomentParams) error {
	_, err := q.db.Exec(ctx, scheduleMoment, arg.ID, arg.ScheduledAt)
	return err
}

const unpublishMoment = `-- name: UnpublishMoment :exec
UPDATE moments
SET publish_status = 'draft', scheduled_at = NULL, published_at = NULL
WHERE id = $1
`

func (q *Queries) UnpublishMoment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unpublishMoment, id)
	return err
}

const updateMoment = `-- name: UpdateMoment :exec
UPDATE moments
SET author_name = $2, author_avatar_url = $3, content = $4, image_urls = $5, publish_status = $6,
    published_at = CASE WHEN $6 = 'published'::moment_publish_status THEN COALESCE(published_at, now()) ELSE NULL::timestamptz END,
    scheduled_at = CASE WHEN $6 = 'scheduled'::moment_publish_status THEN $7::timestamptz ELSE NULL::timestamptz END
WHERE id = $1
`

type UpdateMomentParams struct {
	ID              uuid.UUID           `json:"id"`
	AuthorName      string              `json:"author_name"`
	AuthorAvatarUrl string              `json:"author_avatar_url"`
	Content         string              `json:"content"`
	ImageUrls       json.RawMessage     `json:"image_urls"`
	PublishStatus   MomentPublishStatus `json:"publish_status"`
	ScheduledAt     pgtype.Timestamptz  `json:"scheduled_at"`
}

func (q *Queries) UpdateMoment(ctx context.Context, arg UpdateMomentParams) error {
	_, err := q.db.Exec(ctx, updateMoment,
		arg.ID,
		arg.AuthorName,
		arg.AuthorAvatarUrl,
		arg.Content,
		arg.ImageUrls,
		arg.PublishStatus,
		arg.ScheduledAt,
	)
	return err
}
