// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTag = `-- name: AddPostTag :exec
INSERT INTO post_tags (post_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddPostTagParams struct {
	PostID uuid.UUID `json:"post_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.Exec(ctx, addPostTag, arg.PostID, arg.TagID)
	return err
}

const checkPostLike = `-- name: CheckPostLike :one
SELECT count(*) FROM post_likes WHERE post_id = $1 AND visitor_id = $2
`

type CheckPostLikeParams struct {
	PostID    uuid.UUID `json:"post_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CheckPostLike(ctx context.Context, arg CheckPostLikeParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkPostLike, arg.PostID, arg.VisitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminPosts = `-- name: CountAdminPosts :one
SELECT count(*) FROM posts
`

func (q *Queries) CountAdminPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPosts = `-- name: CountPublishedPosts :one
SELECT count(*)
FROM posts
WHERE status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= now()
`

func (q *Queries) CountPublishedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    slug, title, excerpt, content_markdown, hero_image_url, category, status,
    published_at, scheduled_at, created_by, updated_by
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    CASE WHEN $7 = 'published'::post_status THEN now() ELSE NULL END,
    CASE WHEN $7 = 'scheduled'::post_status THEN $9::timestamptz ELSE NULL::timestamptz END,
    $8, $8
)
RETURNING id, created_at
`

type CreatePostParams struct {
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	Excerpt         string      `json:"excerpt"`
	ContentMarkdown string      `json:"content_markdown"`
	HeroImageUrl    string      `json:"hero_image_url"`
	Category        string      `json:"category"`
	Status          PostStatus  `json:"status"`
	CreatedBy       pgtype.UUID `json:"created_by"`
	Column9         time.Time   `json:"column_9"`
}

type CreatePostRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.HeroImageUrl,
		arg.Category,
		arg.Status,
		arg.CreatedBy,
		arg.Column9,
	)
	var i CreatePostRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createPostLike = `-- name: CreatePostLike :exec
INSERT INTO post_likes (post_id, visitor_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreatePostLikeParams struct {
	PostID    uuid.UUID `json:"post_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) error {
	_, err := q.db.Exec(ctx, createPostLike, arg.PostID, arg.VisitorID)
	return err
}

const createPostViewVisitorDaily = `-- name: CreatePostViewVisitorDaily :one
INSERT INTO post_view_daily_visitors (post_id, day, visitor_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING 1
`

type CreatePostViewVisitorDailyParams struct {
	PostID    uuid.UUID   `json:"post_id"`
	Day       pgtype.Date `json:"day"`
	VisitorID uuid.UUID   `json:"visitor_id"`
}

func (q *Queries) CreatePostViewVisitorDaily(ctx context.Context, arg CreatePostViewVisitorDailyParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPostViewVisitorDaily, arg.PostID, arg.Day, arg.VisitorID)
	var marker int32
	err := row.Scan(&marker)
	return marker, err
}

const createPostRevision = `-- name: CreatePostRevision :exec
INSERT INTO post_revisions (post_id, title, excerpt, content_markdown, hero_image_url, category, editor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePostRevisionParams struct {
	PostID          uuid.UUID   `json:"post_id"`
	Title           string      `json:"title"`
	Excerpt         string      `json:"excerpt"`
	ContentMarkdown string      `json:"content_markdown"`
	HeroImageUrl    string      `json:"hero_image_url"`
	Category        string      `json:"category"`
	EditorID        pgtype.UUID `json:"editor_id"`
}

func (q *Queries) CreatePostRevision(ctx context.Context, arg CreatePostRevisionParams) error {
	_, err := q.db.Exec(ctx, createPostRevision,
		arg.PostID,
		arg.Title,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.HeroImageUrl,
		arg.Category,
		arg.EditorID,
	)
	return err
}

const decrementPostCommentCount = `-- name: DecrementPostCommentCount :exec
UPDATE posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementPostCommentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementPostCommentCount, id)
	return err
}

const decrementPostLikeCount = `-- name: DecrementPostLikeCount :exec
UPDATE posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementPostLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementPostLikeCount, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostLike = `-- name: DeletePostLike :exec
DELETE FROM post_likes WHERE post_id = $1 AND visitor_id = $2
`

type DeletePostLikeParams struct {
	PostID    uuid.UUID `json:"post_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error {
	_, err := q.db.Exec(ctx, deletePostLike, arg.PostID, arg.VisitorID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, slug, title, excerpt, content_markdown, hero_image_url, category,
       status, published_at, scheduled_at, view_count, like_count, comment_count,
       created_by, updated_by, created_at, updated_at
FROM posts
WHERE id = $1
`

type GetPostByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Excerpt         string             `json:"excerpt"`
	ContentMarkdown string             `json:"content_markdown"`
	HeroImageUrl    string             `json:"hero_image_url"`
	Category        string             `json:"category"`
	Status          PostStatus         `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	ViewCount       int64              `json:"view_count"`
	LikeCount       int64              `json:"like_count"`
	CommentCount    int64              `json:"comment_count"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.HeroImageUrl,
		&i.Category,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.ViewCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, slug, title, excerpt, content_markdown, hero_image_url, category,
       status, published_at, scheduled_at, view_count, like_count, comment_count,
       created_by, updated_by, created_at, updated_at
FROM posts
WHERE slug = $1
  AND status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= now()
`

type GetPostBySlugRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Excerpt         string             `json:"excerpt"`
	ContentMarkdown string             `json:"content_markdown"`
	HeroImageUrl    string             `json:"hero_image_url"`
	Category        string             `json:"category"`
	Status          PostStatus         `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	ViewCount       int64              `json:"view_count"`
	LikeCount       int64              `json:"like_count"`
	CommentCount    int64              `json:"comment_count"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i GetPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.HeroImageUrl,
		&i.Category,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.ViewCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostRevision = `-- name: GetPostRevision :one
SELECT id, post_id, title, excerpt, content_markdown, hero_image_url, category, editor_id, created_at
FROM post_revisions
WHERE id = $1
`

func (q *Queries) GetPostRevision(ctx context.Context, id uuid.UUID) (PostRevision, error) {
	row := q.db.QueryRow(ctx, getPostRevision, id)
	var i PostRevision
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.HeroImageUrl,
		&i.Category,
		&i.EditorID,
		&i.CreatedAt,
	)
	return i, err
}

const getPostTagNames = `-- name: GetPostTagNames :many
SELECT t.name, t.slug
FROM tags t
JOIN post_tags pt ON pt.tag_id = t.id
WHERE pt.post_id = $1
`

type GetPostTagNamesRow struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) GetPostTagNames(ctx context.Context, postID uuid.UUID) ([]GetPostTagNamesRow, error) {
	rows, err := q.db.Query(ctx, getPostTagNames, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostTagNamesRow{}
	for rows.Next() {
		var i GetPostTagNamesRow
		if err := rows.Scan(&i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPostCommentCount = `-- name: IncrementPostCommentCount :exec
UPDATE posts SET comment_count = comment_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostCommentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPostCommentCount, id)
	return err
}

const incrementPostLikeCount = `-- name: IncrementPostLikeCount :exec
UPDATE posts SET like_count = like_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostLikeCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPostLikeCount, id)
	return err
}

const incrementPostViewCount = `-- name: IncrementPostViewCount :exec
UPDATE posts SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostViewCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPostViewCount, id)
	return err
}

const listAdminPosts = `-- name: ListAdminPosts :many
SELECT id, slug, title, category, status,
       published_at, scheduled_at, view_count, like_count, comment_count,
       created_at, updated_at
FROM posts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminPostsRow struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Category     string             `json:"category"`
	Status       PostStatus         `json:"status"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	ViewCount    int64              `json:"view_count"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) ListAdminPosts(ctx context.Context, arg ListAdminPostsParams) ([]ListAdminPostsRow, error) {
	rows, err := q.db.Query(ctx, listAdminPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminPostsRow{}
	for rows.Next() {
		var i ListAdminPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotPosts = `-- name: ListHotPosts :many
SELECT id, slug, title, excerpt, hero_image_url, category,
       published_at, view_count, like_count, comment_count, created_at
FROM posts
WHERE status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= now()
ORDER BY (view_count + like_count * 3 + comment_count * 5) DESC
LIMIT $1
`

type ListHotPostsRow struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Excerpt      string             `json:"excerpt"`
	HeroImageUrl string             `json:"hero_image_url"`
	Category     string             `json:"category"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	ViewCount    int64              `json:"view_count"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
	CreatedAt    time.Time          `json:"created_at"`
}

func (q *Queries) ListHotPosts(ctx context.Context, limit int32) ([]ListHotPostsRow, error) {
	rows, err := q.db.Query(ctx, listHotPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHotPostsRow{}
	for rows.Next() {
		var i ListHotPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Category,
			&i.PublishedAt,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostRevisions = `-- name: ListPostRevisions :many
SELECT id, post_id, title, excerpt, hero_image_url, category, editor_id, created_at
FROM post_revisions
WHERE post_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostRevisionsParams struct {
	PostID uuid.UUID `json:"post_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListPostRevisionsRow struct {
	ID           uuid.UUID   `json:"id"`
	PostID       uuid.UUID   `json:"post_id"`
	Title        string      `json:"title"`
	Excerpt      string      `json:"excerpt"`
	HeroImageUrl string      `json:"hero_image_url"`
	Category     string      `json:"category"`
	EditorID     pgtype.UUID `json:"editor_id"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) ListPostRevisions(ctx context.Context, arg ListPostRevisionsParams) ([]ListPostRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listPostRevisions, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostRevisionsRow{}
	for rows.Next() {
		var i ListPostRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Title,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Category,
			&i.EditorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByCategory = `-- name: ListPostsByCategory :many
SELECT
    p.id,
    p.slug,
    p.title,
    p.excerpt,
    p.hero_image_url,
    p.category,
    p.published_at,
    p.view_count,
    p.like_count,
    p.comment_count,
    p.created_at,
    COALESCE(array_agg(t.name ORDER BY t.slug) FILTER (WHERE t.id IS NOT NULL), ARRAY[]::text[]) AS tag_names,
    COALESCE(array_agg(t.slug ORDER BY t.slug) FILTER (WHERE t.id IS NOT NULL), ARRAY[]::text[]) AS tag_slugs
FROM posts p
LEFT JOIN post_tags pt ON pt.post_id = p.id
LEFT JOIN tags t ON t.id = pt.tag_id
WHERE p.status = 'published'
  AND p.published_at IS NOT NULL
  AND p.published_at <= now()
  AND p.category = $1
GROUP BY
    p.id,
    p.slug,
    p.title,
    p.excerpt,
    p.hero_image_url,
    p.category,
    p.published_at,
    p.view_count,
    p.like_count,
    p.comment_count,
    p.created_at
ORDER BY p.published_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByCategoryParams struct {
	Category string `json:"category"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListPostsByCategoryRow struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Excerpt      string             `json:"excerpt"`
	HeroImageUrl string             `json:"hero_image_url"`
	Category     string             `json:"category"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	ViewCount    int64              `json:"view_count"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
	CreatedAt    time.Time          `json:"created_at"`
	TagNames     []string           `json:"tag_names"`
	TagSlugs     []string           `json:"tag_slugs"`
}

func (q *Queries) ListPostsByCategory(ctx context.Context, arg ListPostsByCategoryParams) ([]ListPostsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listPostsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByCategoryRow{}
	for rows.Next() {
		var i ListPostsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Category,
			&i.PublishedAt,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.TagNames,
			&i.TagSlugs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT
    p.id,
    p.slug,
    p.title,
    p.excerpt,
    p.hero_image_url,
    p.category,
    p.status,
    p.published_at,
    p.view_count,
    p.like_count,
    p.comment_count,
    p.created_at,
    COALESCE(array_agg(t.name ORDER BY t.slug) FILTER (WHERE t.id IS NOT NULL), ARRAY[]::text[]) AS tag_names,
    COALESCE(array_agg(t.slug ORDER BY t.slug) FILTER (WHERE t.id IS NOT NULL), ARRAY[]::text[]) AS tag_slugs
FROM posts p
LEFT JOIN post_tags pt ON pt.post_id = p.id
LEFT JOIN tags t ON t.id = pt.tag_id
WHERE p.status = 'published'
  AND p.published_at IS NOT NULL
  AND p.published_at <= now()
GROUP BY
    p.id,
    p.slug,
    p.title,
    p.excerpt,
    p.hero_image_url,
    p.category,
    p.status,
    p.published_at,
    p.view_count,
    p.like_count,
    p.comment_count,
    p.created_at
ORDER BY p.published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedPostsRow struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Excerpt      string             `json:"excerpt"`
	HeroImageUrl string             `json:"hero_image_url"`
	Category     string             `json:"category"`
	Status       PostStatus         `json:"status"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	ViewCount    int64              `json:"view_count"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
	CreatedAt    time.Time          `json:"created_at"`
	TagNames     []string           `json:"tag_names"`
	TagSlugs     []string           `json:"tag_slugs"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPostsRow{}
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Category,
			&i.Status,
			&i.PublishedAt,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.TagNames,
			&i.TagSlugs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPostsDue = `-- name: ListScheduledPostsDue :many
SELECT id, slug, title FROM posts
WHERE status = 'scheduled' AND scheduled_at <= now()
`

type ListScheduledPostsDueRow struct {
	ID    uuid.UUID `json:"id"`
	Slug  string    `json:"slug"`
	Title string    `json:"title"`
}

func (q *Queries) ListScheduledPostsDue(ctx context.Context) ([]ListScheduledPostsDueRow, error) {
	rows, err := q.db.Query(ctx, listScheduledPostsDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledPostsDueRow{}
	for rows.Next() {
		var i ListScheduledPostsDueRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPost = `-- name: PublishPost :exec
UPDATE posts
SET status = 'published', published_at = now(), scheduled_at = NULL, updated_by = $2
WHERE id = $1
`

type PublishPostParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) PublishPost(ctx context.Context, arg PublishPostParams) error {
	_, err := q.db.Exec(ctx, publishPost, arg.ID, arg.UpdatedBy)
	return err
}

const schedulePost = `-- name: SchedulePost :exec
UPDATE posts
SET status = 'scheduled', scheduled_at = $2, published_at = NULL, updated_by = $3
WHERE id = $1
`

type SchedulePostParams struct {
	ID          uuid.UUID          `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) SchedulePost(ctx context.Context, arg SchedulePostParams) error {
	_, err := q.db.Exec(ctx, schedulePost, arg.ID, arg.ScheduledAt, arg.UpdatedBy)
	return err
}

const searchPosts = `-- name: SearchPosts :many
SELECT id, slug, title, excerpt, hero_image_url, category,
       published_at, view_count, like_count, comment_count,
       ts_rank(search_vector, websearch_to_tsquery('simple', $1)) AS rank
FROM posts
WHERE status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= now()
  AND search_vector @@ websearch_to_tsquery('simple', $1)
ORDER BY rank DESC
LIMIT $2 OFFSET $3
`

type SearchPostsParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
	Offset             int32  `json:"offset"`
}

type SearchPostsRow struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Excerpt      string             `json:"excerpt"`
	HeroImageUrl string             `json:"hero_image_url"`
	Category     string             `json:"category"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	ViewCount    int64              `json:"view_count"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
	Rank         float32            `json:"rank"`
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, arg.WebsearchToTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.HeroImageUrl,
			&i.Category,
			&i.PublishedAt,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPostTags = `-- name: SetPostTags :exec
DELETE FROM post_tags WHERE post_id = $1
`

func (q *Queries) SetPostTags(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPostTags, postID)
	return err
}

const unpublishPost = `-- name: UnpublishPost :exec
UPDATE posts
SET status = 'draft', scheduled_at = NULL, updated_by = $2
WHERE id = $1
`

type UnpublishPostParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UnpublishPost(ctx context.Context, arg UnpublishPostParams) error {
	_, err := q.db.Exec(ctx, unpublishPost, arg.ID, arg.UpdatedBy)
	return err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET slug = $2, title = $3, excerpt = $4, content_markdown = $5,
    hero_image_url = $6, category = $7, updated_by = $8, updated_at = now()
WHERE id = $1
`

type UpdatePostParams struct {
	ID              uuid.UUID   `json:"id"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	Excerpt         string      `json:"excerpt"`
	ContentMarkdown string      `json:"content_markdown"`
	HeroImageUrl    string      `json:"hero_image_url"`
	Category        string      `json:"category"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.HeroImageUrl,
		arg.Category,
		arg.UpdatedBy,
	)
	return err
}

const upsertPostViewDaily = `-- name: UpsertPostViewDaily :exec
INSERT INTO post_view_daily (post_id, day, pv, uv)
VALUES ($1, $2, 1, $3)
ON CONFLICT (post_id, day) DO UPDATE
SET pv = post_view_daily.pv + 1,
    uv = post_view_daily.uv + $3
`

type UpsertPostViewDailyParams struct {
	PostID uuid.UUID   `json:"post_id"`
	Day    pgtype.Date `json:"day"`
	Uv     int64       `json:"uv"`
}

func (q *Queries) UpsertPostViewDaily(ctx context.Context, arg UpsertPostViewDailyParams) error {
	_, err := q.db.Exec(ctx, upsertPostViewDaily, arg.PostID, arg.Day, arg.Uv)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name, slug) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.Name, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
