// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPostTag(ctx context.Context, arg AddPostTagParams) error
	ApproveComment(ctx context.Context, arg ApproveCommentParams) error
	ApproveFriendLink(ctx context.Context, arg ApproveFriendLinkParams) error
	ApproveGuestbookMessage(ctx context.Context, arg ApproveGuestbookMessageParams) error
	CheckBlockedIP(ctx context.Context, ipHash string) (int64, error)
	CheckMomentCommentLike(ctx context.Context, arg CheckMomentCommentLikeParams) (int64, error)
	CheckMomentLike(ctx context.Context, arg CheckMomentLikeParams) (int64, error)
	CheckMomentRepost(ctx context.Context, arg CheckMomentRepostParams) (int64, error)
	CheckPostLike(ctx context.Context, arg CheckPostLikeParams) (int64, error)
	CleanExpiredTokens(ctx context.Context) error
	CountAdminComments(ctx context.Context, status NullModerationStatus) (int64, error)
	CountAdminFriendLinks(ctx context.Context) (int64, error)
	CountAdminGuestbookMessages(ctx context.Context, status NullModerationStatus) (int64, error)
	CountAdminMoments(ctx context.Context) (int64, error)
	CountAdminPosts(ctx context.Context) (int64, error)
	CountAnalyticsBouncedVisits(ctx context.Context, arg CountAnalyticsBouncedVisitsParams) (int64, error)
	CountAnalyticsViews(ctx context.Context, arg CountAnalyticsViewsParams) (int64, error)
	CountAnalyticsVisitors(ctx context.Context, arg CountAnalyticsVisitorsParams) (int64, error)
	CountAnalyticsVisits(ctx context.Context, arg CountAnalyticsVisitsParams) (int64, error)
	CountApprovedComments(ctx context.Context, postID uuid.UUID) (int64, error)
	CountApprovedFriendLinks(ctx context.Context) (int64, error)
	CountDraftPosts(ctx context.Context) (int64, error)
	CountGuestbookMessages(ctx context.Context) (int64, error)
	CountMomentComments(ctx context.Context, momentID uuid.UUID) (int64, error)
	CountMoments(ctx context.Context) (int64, error)
	CountPendingComments(ctx context.Context) (int64, error)
	CountPublishedPosts(ctx context.Context) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error)
	CreateAnalyticsPageview(ctx context.Context, arg CreateAnalyticsPageviewParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateFriendLink(ctx context.Context, arg CreateFriendLinkParams) (CreateFriendLinkRow, error)
	CreateFriendLinkHealthLog(ctx context.Context, arg CreateFriendLinkHealthLogParams) error
	CreateGuestbookMessage(ctx context.Context, arg CreateGuestbookMessageParams) (CreateGuestbookMessageRow, error)
	CreateMoment(ctx context.Context, arg CreateMomentParams) (CreateMomentRow, error)
	CreateMomentComment(ctx context.Context, arg CreateMomentCommentParams) (CreateMomentCommentRow, error)
	CreateMomentCommentLike(ctx context.Context, arg CreateMomentCommentLikeParams) error
	CreateMomentLike(ctx context.Context, arg CreateMomentLikeParams) error
	CreateMomentRepost(ctx context.Context, arg CreateMomentRepostParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error)
	CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (CreatePostCommentRow, error)
	CreatePostLike(ctx context.Context, arg CreatePostLikeParams) error
	CreatePostRevision(ctx context.Context, arg CreatePostRevisionParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	CreateVisitor(ctx context.Context, arg CreateVisitorParams) (CreateVisitorRow, error)
	DecrementMomentCommentLikeCount(ctx context.Context, id uuid.UUID) error
	DecrementMomentLikeCount(ctx context.Context, id uuid.UUID) error
	DecrementMomentRepostCount(ctx context.Context, id uuid.UUID) error
	DecrementPostCommentCount(ctx context.Context, id uuid.UUID) error
	DecrementPostLikeCount(ctx context.Context, id uuid.UUID) error
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteFriendLink(ctx context.Context, id uuid.UUID) error
	DeleteGuestbookMessage(ctx context.Context, id uuid.UUID) error
	DeleteGuestbookVote(ctx context.Context, arg DeleteGuestbookVoteParams) error
	DeleteMoment(ctx context.Context, id uuid.UUID) error
	DeleteMomentCommentLike(ctx context.Context, arg DeleteMomentCommentLikeParams) error
	DeleteMomentLike(ctx context.Context, arg DeleteMomentLikeParams) error
	DeleteMomentRepost(ctx context.Context, arg DeleteMomentRepostParams) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error
	ExportBackupPayload(ctx context.Context) (json.RawMessage, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (GetAdminByIDRow, error)
	GetAdminByIdentifier(ctx context.Context, username string) (GetAdminByIdentifierRow, error)
	GetAdminByUsername(ctx context.Context, username string) (GetAdminByUsernameRow, error)
	GetAnalyticsAverageVisitDurationSeconds(ctx context.Context, arg GetAnalyticsAverageVisitDurationSecondsParams) (float64, error)
	GetAnalyticsTrafficHeatmap(ctx context.Context, arg GetAnalyticsTrafficHeatmapParams) ([]GetAnalyticsTrafficHeatmapRow, error)
	GetAnalyticsTrend(ctx context.Context, arg GetAnalyticsTrendParams) ([]GetAnalyticsTrendRow, error)
	GetDailyCommentTrend(ctx context.Context, createdAt time.Time) ([]GetDailyCommentTrendRow, error)
	GetDailyLikeTrend(ctx context.Context, createdAt time.Time) ([]GetDailyLikeTrendRow, error)
	GetDailyViewTrend(ctx context.Context, day pgtype.Date) ([]GetDailyViewTrendRow, error)
	GetFriendLinkByID(ctx context.Context, id uuid.UUID) (FriendLink, error)
	GetGuestbookVote(ctx context.Context, arg GetGuestbookVoteParams) (VoteType, error)
	GetMomentByID(ctx context.Context, id uuid.UUID) (GetMomentByIDRow, error)
	GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error)
	GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error)
	GetPostRevision(ctx context.Context, id uuid.UUID) (PostRevision, error)
	GetPostTagNames(ctx context.Context, postID uuid.UUID) ([]GetPostTagNamesRow, error)
	GetPrimaryAdminPublicProfile(ctx context.Context) (GetPrimaryAdminPublicProfileRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AdminRefreshToken, error)
	GetSiteSetting(ctx context.Context, key string) (SiteSetting, error)
	GetTotalLikeCount(ctx context.Context) (int64, error)
	GetTotalPostCount(ctx context.Context) (int64, error)
	GetVisitorByID(ctx context.Context, id uuid.UUID) (Visitor, error)
	GetVisitorByIPUA(ctx context.Context, arg GetVisitorByIPUAParams) (Visitor, error)
	GetVisitorMomentCommentLikes(ctx context.Context, arg GetVisitorMomentCommentLikesParams) ([]uuid.UUID, error)
	GetVisitorMomentLikes(ctx context.Context, arg GetVisitorMomentLikesParams) ([]uuid.UUID, error)
	GetVisitorMomentReposts(ctx context.Context, arg GetVisitorMomentRepostsParams) ([]uuid.UUID, error)
	GetVisitorVotesForMessages(ctx context.Context, arg GetVisitorVotesForMessagesParams) ([]GetVisitorVotesForMessagesRow, error)
	HideMoment(ctx context.Context, arg HideMomentParams) error
	HideMomentComment(ctx context.Context, arg HideMomentCommentParams) error
	IncrementMomentCommentCount(ctx context.Context, id uuid.UUID) error
	IncrementMomentCommentLikeCount(ctx context.Context, id uuid.UUID) error
	IncrementMomentLikeCount(ctx context.Context, id uuid.UUID) error
	IncrementMomentRepostCount(ctx context.Context, id uuid.UUID) error
	IncrementPostCommentCount(ctx context.Context, id uuid.UUID) error
	IncrementPostLikeCount(ctx context.Context, id uuid.UUID) error
	IncrementPostViewCount(ctx context.Context, id uuid.UUID) error
	ListAdminComments(ctx context.Context, arg ListAdminCommentsParams) ([]ListAdminCommentsRow, error)
	ListAdminFriendLinks(ctx context.Context, arg ListAdminFriendLinksParams) ([]ListAdminFriendLinksRow, error)
	ListAdminGuestbookMessages(ctx context.Context, arg ListAdminGuestbookMessagesParams) ([]ListAdminGuestbookMessagesRow, error)
	ListAdminMoments(ctx context.Context, arg ListAdminMomentsParams) ([]ListAdminMomentsRow, error)
	ListAdminPosts(ctx context.Context, arg ListAdminPostsParams) ([]ListAdminPostsRow, error)
	ListAnalyticsBrowsers(ctx context.Context, arg ListAnalyticsBrowsersParams) ([]ListAnalyticsBrowsersRow, error)
	ListAnalyticsChannels(ctx context.Context, arg ListAnalyticsChannelsParams) ([]ListAnalyticsChannelsRow, error)
	ListAnalyticsCities(ctx context.Context, arg ListAnalyticsCitiesParams) ([]ListAnalyticsCitiesRow, error)
	ListAnalyticsCountries(ctx context.Context, arg ListAnalyticsCountriesParams) ([]ListAnalyticsCountriesRow, error)
	ListAnalyticsDevices(ctx context.Context, arg ListAnalyticsDevicesParams) ([]ListAnalyticsDevicesRow, error)
	ListAnalyticsEntryPaths(ctx context.Context, arg ListAnalyticsEntryPathsParams) ([]ListAnalyticsEntryPathsRow, error)
	ListAnalyticsExitPaths(ctx context.Context, arg ListAnalyticsExitPathsParams) ([]ListAnalyticsExitPathsRow, error)
	ListAnalyticsOperatingSystems(ctx context.Context, arg ListAnalyticsOperatingSystemsParams) ([]ListAnalyticsOperatingSystemsRow, error)
	ListAnalyticsPageStats(ctx context.Context, arg ListAnalyticsPageStatsParams) ([]ListAnalyticsPageStatsRow, error)
	ListAnalyticsReferrers(ctx context.Context, arg ListAnalyticsReferrersParams) ([]ListAnalyticsReferrersRow, error)
	ListAnalyticsRegions(ctx context.Context, arg ListAnalyticsRegionsParams) ([]ListAnalyticsRegionsRow, error)
	ListApprovedComments(ctx context.Context, arg ListApprovedCommentsParams) ([]ListApprovedCommentsRow, error)
	ListApprovedFriendLinks(ctx context.Context) ([]ListApprovedFriendLinksRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListFriendLinksForHealthCheck(ctx context.Context) ([]ListFriendLinksForHealthCheckRow, error)
	ListGuestbookMessages(ctx context.Context, arg ListGuestbookMessagesParams) ([]ListGuestbookMessagesRow, error)
	ListGuestbookReplies(ctx context.Context, parentID pgtype.UUID) ([]ListGuestbookRepliesRow, error)
	ListHotPosts(ctx context.Context, limit int32) ([]ListHotPostsRow, error)
	ListLatestMoments(ctx context.Context, limit int32) ([]ListLatestMomentsRow, error)
	ListMomentComments(ctx context.Context, arg ListMomentCommentsParams) ([]ListMomentCommentsRow, error)
	ListMoments(ctx context.Context, arg ListMomentsParams) ([]ListMomentsRow, error)
	ListPostRevisions(ctx context.Context, arg ListPostRevisionsParams) ([]ListPostRevisionsRow, error)
	ListPostsByCategory(ctx context.Context, arg ListPostsByCategoryParams) ([]ListPostsByCategoryRow, error)
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error)
	ListScheduledMomentsDue(ctx context.Context) ([]uuid.UUID, error)
	ListScheduledPostsDue(ctx context.Context) ([]ListScheduledPostsDueRow, error)
	ListSensitiveWords(ctx context.Context) ([]string, error)
	PublishMoment(ctx context.Context, id uuid.UUID) error
	PublishPost(ctx context.Context, arg PublishPostParams) error
	RecalcGuestbookVoteScore(ctx context.Context, messageID uuid.UUID) error
	RejectComment(ctx context.Context, arg RejectCommentParams) error
	RejectFriendLink(ctx context.Context, arg RejectFriendLinkParams) error
	RejectGuestbookMessage(ctx context.Context, arg RejectGuestbookMessageParams) error
	RevokeAllUserTokens(ctx context.Context, adminUserID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	ScheduleMoment(ctx context.Context, arg ScheduleMomentParams) error
	SchedulePost(ctx context.Context, arg SchedulePostParams) error
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error)
	SetPostTags(ctx context.Context, postID uuid.UUID) error
	TouchRefreshToken(ctx context.Context, id uuid.UUID) error
	TouchVisitor(ctx context.Context, id uuid.UUID) error
	UnpublishMoment(ctx context.Context, id uuid.UUID) error
	UnpublishPost(ctx context.Context, arg UnpublishPostParams) error
	UpdateAdminAccount(ctx context.Context, arg UpdateAdminAccountParams) error
	UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateAdminPasswordByID(ctx context.Context, arg UpdateAdminPasswordByIDParams) error
	UpdateAdminPasswordByUsername(ctx context.Context, arg UpdateAdminPasswordByUsernameParams) (uuid.UUID, error)
	UpdateAdminProfile(ctx context.Context, arg UpdateAdminProfileParams) error
	UpdateFriendLink(ctx context.Context, arg UpdateFriendLinkParams) error
	UpdateFriendLinkHealth(ctx context.Context, arg UpdateFriendLinkHealthParams) error
	UpdateMoment(ctx context.Context, arg UpdateMomentParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) error
	UpsertAnalyticsSession(ctx context.Context, arg UpsertAnalyticsSessionParams) (UpsertAnalyticsSessionRow, error)
	UpsertGuestbookVote(ctx context.Context, arg UpsertGuestbookVoteParams) error
	UpsertPostViewDaily(ctx context.Context, arg UpsertPostViewDailyParams) error
	UpsertSiteSetting(ctx context.Context, arg UpsertSiteSettingParams) (SiteSetting, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
