// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_settings.sql

package query

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSiteSetting = `-- name: GetSiteSetting :one
SELECT key, value, created_at, updated_at, updated_by
FROM site_settings
WHERE key = $1
`

func (q *Queries) GetSiteSetting(ctx context.Context, key string) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSetting, key)
	var i SiteSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertSiteSetting = `-- name: UpsertSiteSetting :one
INSERT INTO site_settings (key, value, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING key, value, created_at, updated_at, updated_by
`

type UpsertSiteSettingParams struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedBy pgtype.UUID     `json:"updated_by"`
}

func (q *Queries) UpsertSiteSetting(ctx context.Context, arg UpsertSiteSettingParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSiteSetting, arg.Key, arg.Value, arg.UpdatedBy)
	var i SiteSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
